-- ── Loja Logística — Seed Data ───────────────────────────────────────
-- Run AFTER schema.sql in the Supabase SQL editor.
-- Inserts 12 suppliers and ~420 products.

-- ── Suppliers ────────────────────────────────────────────────────────

INSERT INTO suppliers (id, name, tagline, category, whatsapp, address, cnpj, hero) VALUES
  ('hortifruti', 'Hortifruti Verde Vale', 'Frutas, legumes e verduras direto do produtor', 'Hortifruti', '5511991111111', 'CEAGESP — Pavilhão MLP, Box 24', '12.345.678/0001-01', 'vegetables,market'),
  ('acougue',    'Açougue Boi Bom',       'Cortes nobres e diários para o food service',   'Açougue',    '5511992222222', 'Av. das Carnes, 1240 — Vila Industrial',   '23.456.789/0001-02', 'butcher,meat'),
  ('laticinios', 'Laticínios Bela Vista', 'Queijos, leites e derivados frescos',           'Laticínios', '5511993333333', 'Estrada do Leite, km 12 — Zona Rural',    '34.567.890/0001-03', 'cheese,dairy'),
  ('padaria',    'Padaria Pão Quente',    'Pães, doces e salgados feitos hoje',            'Panificação','5511994444444', 'Rua das Padarias, 88 — Centro',           '45.678.901/0001-04', 'bread,bakery'),
  ('mercearia',  'Mercearia do Bairro',   'Itens de prateleira para o dia a dia',          'Mercearia',  '5511995555555', 'Av. Comercial, 555 — Bairro do Mercado',  '56.789.012/0001-05', 'grocery,store'),
  ('bebidas',    'Bebidas Refresca',      'Refrigerantes, sucos, águas e energéticos',     'Bebidas',    '5511996666666', 'Rod. dos Bandeirantes, km 35 — CD Bebidas','67.890.123/0001-06', 'beverage,drinks'),
  ('limpeza',    'Limpeza Brilho Total',  'Higiene e limpeza profissional',                'Limpeza',    '5511997777777', 'Rua Industrial, 100 — Galpão 5',          '78.901.234/0001-07', 'cleaning,products'),
  ('embalagens', 'Embalagens Pratika',    'Embalagens, descartáveis e sacolas',            'Embalagens', '5511998888888', 'Rua dos Plásticos, 240 — Distrito Industrial','89.012.345/0001-08','packaging,boxes'),
  ('doces',      'Doce Mel',              'Balas, chocolates e confeitos',                 'Doces',      '5511999999999', 'Rua das Confeitarias, 78',                '90.123.456/0001-09', 'candy,sweets'),
  ('congelados', 'Congelados Antártida',  'Praticidade e qualidade no freezer',            'Congelados', '5511990000001', 'Rua do Frio, 200 — Galpão 2',             '01.234.567/0001-10', 'frozen,food'),
  ('cafes',      'Café & Cia',            'Cafés especiais, chás e cápsulas',              'Cafés e Chás','5511990000002','Rua dos Cafés, 333',                      '11.222.333/0001-11', 'coffee,beans'),
  ('pescados',   'Distribuidora Sul Mar', 'Pescados frescos e congelados',                 'Pescados',   '5511990000003', 'Mercado do Peixe, Box 14',                '22.333.444/0001-12', 'fish,seafood')
ON CONFLICT (id) DO NOTHING;

-- ── Products ─────────────────────────────────────────────────────────
-- Format: (supplier_id, name, brand, unit, price, min_order, description, in_stock, keyword)

INSERT INTO products (supplier_id, name, brand, unit, price, min_order, description, in_stock, keyword) VALUES
-- Hortifruti
('hortifruti','Banana Prata','Sítio Boa Vista','kg',6.90,5,'Cacho com pencas firmes, ponto de maduração regular.',true,'banana'),
('hortifruti','Maçã Fuji','Pomar Catarina','kg',9.50,3,'Cat. Extra, calibre 110-130, polpa crocante.',true,'apple,red'),
('hortifruti','Tomate Italiano','Sítio Boa Vista','kg',7.80,5,'Para molho — polpa firme, baixa acidez.',true,'tomato'),
('hortifruti','Alface Crespa','Verduras Frescas','un',3.20,10,'Pé inteiro, lavado e embalado a vácuo.',true,'lettuce'),
('hortifruti','Cenoura','Sítio Boa Vista','kg',4.90,5,'Cat. comum, raiz limpa e sem rachaduras.',true,'carrot'),
('hortifruti','Cebola Branca','Cebolas do Sul','kg',5.40,10,'Cat. 3, casca seca e firme.',true,'onion'),
('hortifruti','Batata Inglesa','Cooperativa Serrana','kg',4.20,10,'Lavada, cat. especial, embalagem 50kg.',true,'potato'),
('hortifruti','Limão Tahiti','Cítricos Norte','kg',7.10,3,'Casca lisa, alto rendimento de suco.',true,'lime'),
('hortifruti','Abacaxi Pérola','Frutas do Norte','un',8.90,5,'Doçura média, ideal para sucos e sobremesas.',true,'pineapple'),
('hortifruti','Mamão Formosa','Frutas do Norte','kg',6.40,3,'Maduro, polpa rosada, casca lisa.',true,'papaya'),
('hortifruti','Manga Palmer','Frutas do Norte','kg',8.20,3,'Cat. especial, ponto de maturação regular.',true,'mango'),
('hortifruti','Melancia','Frutas do Norte','kg',3.50,10,'Cat. especial, peso médio 8-12kg por unidade.',true,'watermelon'),
('hortifruti','Pepino Caipira','Verduras Frescas','kg',5.80,3,'Casca verde, sem manchas.',true,'cucumber'),
('hortifruti','Pimentão Vermelho','Verduras Frescas','kg',9.90,3,'Cat. extra, polpa grossa.',true,'pepper,red'),
('hortifruti','Couve Manteiga','Verduras Frescas','maço',3.50,10,'Maço com 12-15 folhas, lavado.',true,'kale'),
('hortifruti','Brócolis Ninja','Verduras Frescas','un',6.20,5,'Floretes compactos, talo curto.',true,'broccoli'),
('hortifruti','Espinafre','Verduras Frescas','maço',4.50,5,'Folhas tenras, sem maço amarelado.',true,'spinach'),
('hortifruti','Rúcula','Verduras Frescas','maço',3.80,10,'Folhas pequenas, sabor acentuado.',true,'arugula'),
('hortifruti','Salsinha','Verduras Frescas','maço',2.40,10,'Maço fresco, lavado.',true,'parsley'),
('hortifruti','Cebolinha','Verduras Frescas','maço',2.40,10,'Maço fresco, lavado.',true,'chives'),
('hortifruti','Beterraba','Sítio Boa Vista','kg',5.10,5,'Cat. extra, sem brotos.',true,'beetroot'),
('hortifruti','Abobrinha','Verduras Frescas','kg',6.80,3,'Cat. comum, casca lisa.',true,'zucchini'),
('hortifruti','Berinjela','Verduras Frescas','kg',6.30,3,'Polpa firme, brilho intenso.',true,'eggplant'),
('hortifruti','Chuchu','Sítio Boa Vista','kg',4.10,5,'Cat. comum, polpa branca.',true,'chayote'),
('hortifruti','Mandioquinha','Cooperativa Serrana','kg',9.90,3,'Cat. especial, sem fibras.',true,'parsnip'),
('hortifruti','Inhame','Sítio Boa Vista','kg',7.20,3,'Cat. comum, peso médio 0,5-1kg.',true,'yam'),
('hortifruti','Milho Verde','Cooperativa Serrana','dúzia',12.00,1,'Espigas frescas, grãos cheios.',false,'corn'),
('hortifruti','Coentro','Verduras Frescas','maço',2.80,10,'Maço fresco, sem amarelados.',true,'cilantro'),
('hortifruti','Manjericão','Verduras Frescas','maço',4.20,5,'Folhas grandes, aroma intenso.',true,'basil'),
('hortifruti','Pera Williams','Pomar Catarina','kg',12.50,3,'Importada, polpa suculenta.',true,'pear'),
('hortifruti','Uva Itália','Vinhedos Sul','kg',14.80,2,'Cacho compacto, sabor doce.',true,'grapes'),
('hortifruti','Morango','Cooperativa Serrana','bdj',7.90,5,'Bandeja com 250g, fruta firme.',true,'strawberry'),
('hortifruti','Laranja Pera','Cítricos Norte','kg',4.40,10,'Para suco, alto rendimento.',true,'orange'),
('hortifruti','Mexerica Ponkan','Cítricos Norte','kg',6.80,5,'Cat. especial, doçura alta.',true,'mandarin,citrus'),
('hortifruti','Kiwi','Pomar Catarina','kg',18.90,1,'Importado do Chile, polpa firme.',false,'kiwi'),
-- Açougue
('acougue','Picanha Bovina','Friboi','kg',89.90,1,'Peça inteira, capa de gordura padrão exportação.',true,'picanha,beef'),
('acougue','Alcatra','Friboi','kg',54.90,1,'Peça inteira, marmoreio regular.',true,'beef,steak'),
('acougue','Contrafilé','Friboi','kg',62.50,1,'Cat. especial, manta inteira.',true,'striploin,beef'),
('acougue','Filé Mignon','Marfrig','kg',119.90,1,'Peça limpa, sem cordão.',true,'filet,mignon'),
('acougue','Coxão Mole','Friboi','kg',42.90,1,'Para bifes e estrogonofe.',true,'beef,roast'),
('acougue','Coxão Duro','Friboi','kg',38.90,1,'Para cozidos e moído.',true,'beef,roast'),
('acougue','Patinho','Friboi','kg',44.50,1,'Cat. extra, baixo teor de gordura.',true,'beef,raw'),
('acougue','Acém','JBS','kg',32.90,1,'Para ensopados e moído.',true,'beef,chuck'),
('acougue','Costela Bovina','JBS','kg',34.90,2,'Tira fina, ideal para churrasco.',true,'beef,ribs'),
('acougue','Fraldinha','Friboi','kg',48.90,1,'Manta inteira, fibras longas.',true,'flank,steak'),
('acougue','Maminha','Friboi','kg',56.90,1,'Peça inteira, capa de gordura.',true,'tri,tip,beef'),
('acougue','Cupim','Marfrig','kg',39.90,1,'Peça inteira, ideal para assar.',true,'cupim,brazilian,bbq'),
('acougue','Carne Moída 2ª','Friboi','kg',28.90,2,'Moída na hora, embalagem a vácuo.',true,'ground,beef'),
('acougue','Músculo','Friboi','kg',32.50,1,'Para sopas e cozidos longos.',true,'beef,stew'),
('acougue','Língua Bovina','JBS','kg',38.90,1,'Limpa, embalada a vácuo.',true,'tongue,beef'),
('acougue','Coração de Frango','Sadia','kg',24.90,1,'Limpos, embalagem 1kg.',true,'chicken,heart'),
('acougue','Peito de Frango','Sadia','kg',22.50,2,'Sem osso, sem pele, embalagem 1kg.',true,'chicken,breast'),
('acougue','Coxa e Sobrecoxa','Sadia','kg',16.90,2,'Resfriadas, com osso.',true,'chicken,thigh'),
('acougue','Asa de Frango','Perdigão','kg',18.90,2,'Resfriadas, embalagem 1kg.',true,'chicken,wings'),
('acougue','Frango Inteiro','Sadia','kg',14.90,2,'Resfriado, peso médio 2kg.',true,'chicken,raw'),
('acougue','Linguiça Toscana','Aurora','kg',26.90,2,'Pura suína, embalagem 1kg.',true,'sausage,pork'),
('acougue','Linguiça Calabresa','Sadia','kg',32.90,1,'Curada, ideal para pizzas.',true,'pepperoni,sausage'),
('acougue','Bacon em Cubos','Sadia','kg',38.90,1,'Cubos prontos para uso.',true,'bacon'),
('acougue','Bacon em Manta','Sadia','kg',42.50,1,'Manta inteira, defumado.',true,'bacon,strips'),
('acougue','Costela Suína','Aurora','kg',28.90,2,'Tira inteira, ideal para assar.',true,'pork,ribs'),
('acougue','Pernil Suíno','Aurora','kg',24.90,2,'Sem osso, peça inteira.',true,'pork,leg'),
('acougue','Lombo Suíno','Aurora','kg',26.90,1,'Peça inteira, baixa gordura.',true,'pork,loin'),
('acougue','Salsicha Hot Dog','Sadia','pct',12.90,5,'Pacote 500g, 12 unidades.',true,'hotdog,sausage'),
('acougue','Hambúrguer Bovino','Seara','pct',24.90,5,'Pacote com 56 unidades de 56g.',true,'hamburger,patty'),
('acougue','Almôndegas','Seara','pct',19.90,3,'Bovinas congeladas, pacote 1kg.',true,'meatballs'),
('acougue','Costela de Cordeiro','Marfrig','kg',89.90,1,'Importada do Uruguai.',false,'lamb,ribs'),
('acougue','Pernil de Cordeiro','Marfrig','kg',78.90,1,'Sem osso, peça inteira.',false,'lamb,leg'),
('acougue','Maminha Suína','Aurora','kg',22.90,1,'Cat. extra, com capa de gordura.',true,'pork,raw'),
('acougue','Carré de Cordeiro','Marfrig','kg',99.90,1,'Francês, embalagem a vácuo.',true,'rack,lamb'),
('acougue','Carne Moída Especial','Friboi','kg',36.90,1,'Patinho moído, baixa gordura.',true,'ground,beef'),
-- Laticínios
('laticinios','Leite Integral','Itambé','L',5.90,12,'Caixa 1L, longa vida.',true,'milk,carton'),
('laticinios','Leite Desnatado','Itambé','L',6.40,12,'Caixa 1L, zero gordura.',true,'milk,glass'),
('laticinios','Leite Semidesnatado','Piracanjuba','L',6.10,12,'Caixa 1L.',true,'milk,bottle'),
('laticinios','Queijo Mussarela','Tirolez','kg',42.90,1,'Peça inteira ou fatiada.',true,'mozzarella,cheese'),
('laticinios','Queijo Prato','Tirolez','kg',44.90,1,'Peça padrão, fatias finas.',true,'cheese,wheel'),
('laticinios','Queijo Parmesão','Faixa Azul','kg',78.90,1,'Maturado 12 meses, ralado ou em cunha.',true,'parmesan,cheese'),
('laticinios','Queijo Coalho','Vigor','kg',48.90,1,'Espetinhos prontos, embalagem 500g.',true,'cheese,grilled'),
('laticinios','Queijo Minas Frescal','Tirolez','kg',32.90,1,'Peça 500g, salgado leve.',true,'cheese,fresh'),
('laticinios','Requeijão','Catupiry','pote',14.90,6,'Pote 200g, original.',true,'cream,cheese'),
('laticinios','Cream Cheese','Polenghi','pote',18.90,4,'Pote 150g, tradicional.',true,'creamcheese'),
('laticinios','Manteiga sem Sal','Aviação','pct',14.50,6,'Tablete 200g, sem sal.',true,'butter'),
('laticinios','Manteiga com Sal','Aviação','pct',14.50,6,'Tablete 200g, com sal.',true,'butter,salt'),
('laticinios','Iogurte Natural','Vigor','L',8.90,6,'Pote 1L, sem açúcar.',true,'yogurt'),
('laticinios','Iogurte de Morango','Danone','pct',9.90,4,'Bandeja com 6 potes de 100g.',true,'yogurt,strawberry'),
('laticinios','Iogurte Grego','Vigor','pote',7.90,6,'Pote 130g, tradicional.',true,'greek,yogurt'),
('laticinios','Creme de Leite UHT','Itambé','cx',4.50,12,'Caixa 200g, longa vida.',true,'cream,milk'),
('laticinios','Leite Condensado','Moça','cx',7.20,12,'Caixa 395g.',true,'condensed,milk'),
('laticinios','Leite em Pó Integral','Ninho','lata',28.90,4,'Lata 400g, integral.',true,'powder,milk'),
('laticinios','Queijo Gorgonzola','Faixa Azul','kg',89.90,1,'Importado, peça 200g.',false,'gorgonzola,cheese'),
('laticinios','Queijo Provolone','Tirolez','kg',64.90,1,'Peça defumada inteira.',true,'provolone,cheese'),
('laticinios','Queijo Brie','President','pct',32.90,2,'Peça 200g, importado da França.',true,'brie,cheese'),
('laticinios','Queijo Camembert','President','pct',32.90,2,'Peça 250g, importado.',true,'camembert,cheese'),
('laticinios','Ricota Fresca','Tirolez','kg',28.90,1,'Peça 500g, sem sal.',true,'ricotta,cheese'),
('laticinios','Iogurte Desnatado','Vigor','L',8.90,6,'Pote 1L, zero gordura.',true,'yogurt,plain'),
('laticinios','Doce de Leite','Mococa','pote',16.90,4,'Pote 600g, tradicional.',true,'dulce,leche'),
('laticinios','Achocolatado em Pó','Nescau','pct',14.90,6,'Pacote 400g, refil.',true,'chocolate,powder'),
('laticinios','Manteiga de Garrafa','Aviação','L',38.90,1,'Garrafa 500ml, do sertão.',true,'butter,oil'),
('laticinios','Queijo Cottage','Vigor','pote',12.90,4,'Pote 200g, baixa gordura.',true,'cottage,cheese'),
('laticinios','Queijo Reino','Polenghi','kg',84.90,1,'Peça inteira, defumado.',true,'cheese,red'),
('laticinios','Queijo Canastra','Tirolez','kg',92.90,1,'Mineiro artesanal, maturado 22 dias.',false,'mountain,cheese'),
('laticinios','Iogurte Coalhada','Vigor','pote',7.50,6,'Pote 130g.',true,'yogurt'),
('laticinios','Bebida Láctea','Itambé','L',4.90,6,'Pote 1kg, sabor morango.',true,'milk,bottle'),
('laticinios','Queijo Mineiro Padrão','Tirolez','kg',38.90,1,'Peça 700g, levemente salgado.',true,'cheese,white'),
('laticinios','Margarina','Qualy','pote',12.90,6,'Pote 500g, com sal.',true,'margarine'),
('laticinios','Nata','Tirolez','pote',14.90,4,'Pote 300g, fresca.',true,'cream'),
-- Padaria
('padaria','Pão Francês','Casa','kg',18.90,1,'Assado na hora, casca crocante.',true,'french,bread'),
('padaria','Pão de Forma','Wickbold','pct',9.90,6,'Pacote 500g, fatiado.',true,'sliced,bread'),
('padaria','Pão de Hambúrguer','Casa','pct',14.90,4,'Pacote com 8 unidades.',true,'hamburger,bun'),
('padaria','Pão de Hot Dog','Casa','pct',14.90,4,'Pacote com 10 unidades.',true,'hotdog,bun'),
('padaria','Pão Sírio','Casa','pct',12.90,4,'Pacote com 6 unidades.',true,'pita,bread'),
('padaria','Pão Italiano','Casa','un',16.90,4,'Peça 500g, casca rústica.',true,'italian,bread'),
('padaria','Pão Integral','Wickbold','pct',11.90,6,'Pacote 500g, fatiado.',true,'wholewheat,bread'),
('padaria','Pão Australiano','Casa','un',18.90,3,'Peça 400g, com mel e malte.',true,'rye,bread'),
('padaria','Pão de Queijo Cru','Forno de Minas','pct',22.90,3,'Congelado, pacote 1kg.',true,'cheese,bread'),
('padaria','Pão de Queijo Assado','Casa','kg',38.90,1,'Assado na hora.',true,'cheese,puff'),
('padaria','Coxinha de Frango','Casa','un',7.90,12,'Recheio de frango desfiado.',true,'coxinha,brazilian'),
('padaria','Esfiha de Carne','Casa','un',6.50,12,'Massa fina, recheio temperado.',true,'esfiha,middle,east'),
('padaria','Pastel de Queijo','Casa','un',7.20,12,'Massa frita, queijo derretido.',true,'pastel,fried'),
('padaria','Empada de Frango','Casa','un',8.50,6,'Massa amanteigada, recheio cremoso.',true,'empada,brazilian'),
('padaria','Quibe Frito','Casa','un',7.90,12,'Recheio de carne moída.',true,'kibe,arabic'),
('padaria','Bolo de Cenoura','Casa','un',32.90,1,'Bolo inteiro, cobertura de chocolate.',true,'carrot,cake'),
('padaria','Bolo de Fubá','Casa','un',28.90,1,'Receita tradicional.',true,'cornmeal,cake'),
('padaria','Bolo de Chocolate','Casa','un',36.90,1,'Recheio e cobertura de brigadeiro.',true,'chocolate,cake'),
('padaria','Brigadeiro','Casa','un',4.50,24,'Tradicional, granulado.',true,'brigadeiro,sweet'),
('padaria','Beijinho','Casa','un',4.50,24,'Coco e cravo.',true,'coconut,sweet'),
('padaria','Sonho','Casa','un',8.90,6,'Recheio de creme, açúcar polvilhado.',true,'donut,cream'),
('padaria','Croissant','Casa','un',9.90,6,'Folhado amanteigado.',true,'croissant'),
('padaria','Pão Doce','Casa','un',5.90,12,'Recheio de creme.',true,'sweet,bun'),
('padaria','Bisnaguinha','Pullman','pct',7.90,6,'Pacote 300g, doce e macia.',true,'sweet,roll'),
('padaria','Pão Sovado','Casa','un',14.90,4,'Tipo cabocla, peça 500g.',true,'sandwich,roll'),
('padaria','Torrada','Bauducco','pct',8.90,6,'Pacote 160g, tradicional.',true,'toast,bread'),
('padaria','Biscoito de Polvilho','Casa','pct',9.90,6,'Pacote 300g, doce.',true,'biscuit,white'),
('padaria','Empadão de Frango','Casa','un',48.90,1,'Forma 25cm, serve 8.',true,'empadao,pie'),
('padaria','Quiche Lorraine','Casa','un',52.90,1,'Forma 22cm, com bacon e queijo.',true,'quiche,bacon'),
('padaria','Salgados Mistos','Casa','cento',280.00,1,'Cento variado para festa.',false,'finger,food'),
('padaria','Doces Mistos','Casa','cento',220.00,1,'Cento variado para festa.',true,'sweets,assorted'),
('padaria','Bolo Confeitado','Casa','un',89.90,1,'Forma 25cm, recheio à escolha.',true,'cake,decorated'),
('padaria','Pão Recheado','Casa','un',24.90,2,'Recheio de presunto e queijo.',true,'stuffed,bread'),
('padaria','Folhado de Frango','Casa','un',8.90,6,'Massa folhada, recheio cremoso.',true,'pastry,puff'),
-- Mercearia
('mercearia','Arroz Branco Tipo 1','Tio João','pct',28.90,5,'Pacote 5kg, agulhinha.',true,'rice,bag'),
('mercearia','Feijão Carioca','Camil','pct',9.90,6,'Pacote 1kg, tipo 1.',true,'beans,brown'),
('mercearia','Feijão Preto','Camil','pct',10.50,6,'Pacote 1kg.',true,'black,beans'),
('mercearia','Açúcar Refinado','União','pct',5.20,12,'Pacote 1kg.',true,'sugar,white'),
('mercearia','Açúcar Cristal','Caravelas','pct',4.50,12,'Pacote 1kg.',true,'sugar,cristal'),
('mercearia','Sal Refinado','Cisne','pct',3.40,12,'Pacote 1kg.',true,'salt,white'),
('mercearia','Óleo de Soja','Soya','cx',8.90,12,'Garrafa 900ml.',true,'cooking,oil'),
('mercearia','Azeite Extra Virgem','Gallo','gl',39.90,4,'Garrafa 500ml, importado.',true,'olive,oil'),
('mercearia','Vinagre de Maçã','Castelo','gl',8.90,6,'Garrafa 750ml.',true,'apple,vinegar'),
('mercearia','Vinagre Branco','Castelo','gl',4.90,6,'Garrafa 750ml.',true,'vinegar,bottle'),
('mercearia','Macarrão Espaguete','Barilla','pct',6.90,6,'Pacote 500g, sêmola.',true,'spaghetti,pasta'),
('mercearia','Macarrão Penne','Barilla','pct',6.90,6,'Pacote 500g.',true,'penne,pasta'),
('mercearia','Macarrão Parafuso','Adria','pct',5.50,6,'Pacote 500g.',true,'pasta,fusilli'),
('mercearia','Molho de Tomate','Pomarola','cx',4.20,12,'Caixa 340g, tradicional.',true,'tomato,sauce'),
('mercearia','Extrato de Tomate','Quero','lata',4.90,12,'Lata 340g.',true,'tomato,paste'),
('mercearia','Farinha de Trigo','Dona Benta','pct',6.90,6,'Pacote 1kg.',true,'flour,wheat'),
('mercearia','Farinha de Mandioca','Yoki','pct',8.90,4,'Pacote 500g, torrada.',true,'flour,cassava'),
('mercearia','Farinha de Milho','Yoki','pct',5.90,4,'Pacote 500g.',true,'cornmeal'),
('mercearia','Fubá','Sinhá','pct',4.50,6,'Pacote 1kg, mimoso.',true,'corn,flour'),
('mercearia','Aveia em Flocos','Quaker','pct',8.90,4,'Pacote 500g.',true,'oats,flake'),
('mercearia','Café Torrado e Moído','Pilão','pct',18.90,6,'Pacote 500g, tradicional.',true,'coffee,powder'),
('mercearia','Café em Grãos','Melitta','pct',28.90,4,'Pacote 500g, espresso.',true,'coffee,bean'),
('mercearia','Achocolatado em Pó','Nescau','pct',14.90,6,'Pacote 400g.',true,'cocoa,powder'),
('mercearia','Maionese','Hellmanns','pote',14.90,6,'Pote 500g.',true,'mayonnaise,jar'),
('mercearia','Catchup','Heinz','gl',12.90,6,'Bisnaga 397g.',true,'ketchup,bottle'),
('mercearia','Mostarda','Heinz','gl',10.90,6,'Bisnaga 200g.',true,'mustard,bottle'),
('mercearia','Molho Inglês','Lea Perrins','gl',18.90,4,'Garrafa 150ml.',true,'sauce,bottle'),
('mercearia','Tempero Pronto','Sazón','cx',4.90,12,'Caixa 60g, completo.',true,'spice,box'),
('mercearia','Caldo em Tablete','Knorr','cx',5.90,12,'Caixa com 6 cubos.',true,'bouillon,cube'),
('mercearia','Lentilha','Camil','pct',12.90,4,'Pacote 500g.',true,'lentils,brown'),
('mercearia','Grão de Bico','Camil','pct',14.90,4,'Pacote 500g.',true,'chickpeas'),
('mercearia','Ervilha em Conserva','Quero','lata',5.90,12,'Lata 200g.',true,'peas,canned'),
('mercearia','Milho em Conserva','Quero','lata',5.90,12,'Lata 200g.',true,'corn,canned'),
('mercearia','Atum Sólido','Gomes da Costa','lata',14.90,6,'Lata 170g, em água e sal.',true,'tuna,canned'),
('mercearia','Sardinha em Óleo','Coqueiro','lata',9.90,6,'Lata 125g.',false,'sardine,canned'),
-- Bebidas
('bebidas','Refrigerante Cola 2L','Marca Cola','gf',9.90,6,'Garrafa 2L, regular.',true,'soda,bottle'),
('bebidas','Refrigerante Cola Lata','Marca Cola','lata',4.90,12,'Lata 350ml.',true,'soda,can'),
('bebidas','Refrigerante Guaraná 2L','Marca Guaraná','gf',8.90,6,'Garrafa 2L.',true,'guarana,soda'),
('bebidas','Refrigerante Laranja','Marca Laranja','gf',8.50,6,'Garrafa 2L.',true,'orange,soda'),
('bebidas','Refrigerante Limão','Marca Limão','gf',8.50,6,'Garrafa 2L.',true,'lemon,soda'),
('bebidas','Refrigerante Uva','Marca Uva','gf',7.90,6,'Garrafa 2L.',true,'grape,soda'),
('bebidas','Água Mineral 500ml','Crystal','pct',14.90,4,'Fardo com 12 garrafas.',true,'mineral,water'),
('bebidas','Água Mineral 1.5L','Crystal','gf',4.50,6,'Garrafa 1.5L sem gás.',true,'water,bottle'),
('bebidas','Água com Gás','Crystal','gf',4.90,6,'Garrafa 500ml.',true,'sparkling,water'),
('bebidas','Suco de Laranja','Del Valle','cx',8.90,6,'Caixa 1L, néctar.',true,'orange,juice'),
('bebidas','Suco de Uva Integral','Aurora','gf',22.90,4,'Garrafa 1.5L, sem açúcar.',true,'grape,juice'),
('bebidas','Suco de Maçã','Del Valle','cx',8.90,6,'Caixa 1L.',true,'apple,juice'),
('bebidas','Suco de Pêssego','Del Valle','cx',8.90,6,'Caixa 1L.',true,'peach,juice'),
('bebidas','Néctar de Goiaba','Maguary','cx',7.90,6,'Caixa 1L.',true,'guava,juice'),
('bebidas','Chá Mate Gelado','Leão','gf',6.90,6,'Garrafa 1.5L, natural.',true,'iced,tea'),
('bebidas','Chá Verde Gelado','Leão','gf',7.50,6,'Garrafa 1.5L.',true,'green,tea'),
('bebidas','Energético 2L','Marca Energy','gf',22.90,4,'Garrafa 2L.',true,'energy,drink'),
('bebidas','Energético Lata','Marca Energy','lata',9.90,12,'Lata 269ml.',true,'energy,can'),
('bebidas','Isotônico Limão','Gatorade','gf',7.90,6,'Garrafa 500ml.',true,'sports,drink'),
('bebidas','Isotônico Tangerina','Gatorade','gf',7.90,6,'Garrafa 500ml.',true,'sports,drink'),
('bebidas','Água de Coco','Kero Coco','cx',9.90,6,'Caixa 1L, integral.',true,'coconut,water'),
('bebidas','Leite de Coco','Sococo','gf',8.90,6,'Garrafa 200ml.',true,'coconut,milk'),
('bebidas','Cerveja Pilsen Long Neck','Marca Beer','pct',78.90,2,'Pack com 12 unidades, 355ml.',false,'beer,longneck'),
('bebidas','Cerveja Lata 350ml','Marca Beer','pct',64.90,2,'Fardo com 12 latas.',false,'beer,can'),
('bebidas','Refresco em Pó','Tang','cx',1.90,24,'Sachê 25g, vários sabores.',true,'powder,drink'),
('bebidas','Xarope para Drink','Monin','gf',38.90,2,'Garrafa 700ml, sabor caramelo.',true,'syrup,bottle'),
('bebidas','Xarope de Groselha','Milani','gf',14.90,4,'Garrafa 900ml.',true,'syrup,red'),
('bebidas','Soda Limonada','Antarctica','gf',6.90,6,'Garrafa 2L.',true,'lemonade,soda'),
('bebidas','Tônica','Schweppes','lata',5.90,12,'Lata 350ml.',true,'tonic,water'),
('bebidas','Suco em Pó Maracujá','Maguary','cx',1.90,24,'Sachê 25g.',true,'passionfruit,powder'),
('bebidas','Café Gelado','Nescafé','gf',8.90,6,'Garrafa 270ml.',true,'iced,coffee'),
('bebidas','Coquetel Não Alcoólico','Vibe','gf',12.90,6,'Garrafa 275ml, mojito.',true,'cocktail'),
('bebidas','Refresco de Caju','Maguary','cx',9.90,6,'Caixa 1L.',true,'cashew,juice'),
('bebidas','Açaí Polpa','Petruz','pct',18.90,4,'Pacote 4x100g, congelado.',true,'acai,bowl'),
('bebidas','Chá Camomila','Leão','cx',8.90,4,'Caixa com 25 sachês.',true,'tea,bag'),
-- Limpeza
('limpeza','Detergente Líquido','Ypê','gf',3.90,12,'Garrafa 500ml, neutro.',true,'detergent,bottle'),
('limpeza','Detergente em Pó','Omo','cx',32.90,4,'Caixa 2kg, multiação.',true,'powder,detergent'),
('limpeza','Sabão em Barra','Ypê','pct',9.90,6,'Pacote com 5 unidades.',true,'soap,bar'),
('limpeza','Sabão Líquido para Roupas','Omo','gf',28.90,4,'Garrafa 3L, concentrado.',true,'liquid,soap'),
('limpeza','Amaciante de Roupas','Comfort','gf',22.90,4,'Garrafa 2L, lavanda.',true,'fabric,softener'),
('limpeza','Água Sanitária','Qboa','gf',5.90,6,'Garrafa 1L.',true,'bleach,bottle'),
('limpeza','Cloro Concentrado','Sanigran','gf',14.90,4,'Galão 5L.',true,'bleach,gallon'),
('limpeza','Multiuso','Veja','gf',9.90,6,'Spray 500ml.',true,'spray,bottle'),
('limpeza','Limpa Vidros','Veja Vidrex','gf',11.90,6,'Spray 500ml.',true,'glass,cleaner'),
('limpeza','Desinfetante Pinho','Pinho Sol','gf',12.90,6,'Garrafa 500ml.',true,'disinfectant'),
('limpeza','Desinfetante Lavanda','Veja','gf',12.90,6,'Garrafa 1L.',true,'lavender,bottle'),
('limpeza','Limpador de Piso','Veja','gf',8.90,6,'Garrafa 750ml.',true,'floor,cleaner'),
('limpeza','Cera para Piso','Cera Mais','lata',16.90,4,'Lata 750ml, incolor.',true,'wax,can'),
('limpeza','Lustra Móveis','Poliflor','gf',14.90,4,'Aerosol 200ml.',true,'furniture,polish'),
('limpeza','Removedor de Manchas','Vanish','gf',22.90,4,'Pó 450g.',true,'stain,remover'),
('limpeza','Esponja de Aço','Bombril','pct',8.90,6,'Pacote com 8.',true,'steel,wool'),
('limpeza','Esponja Dupla Face','Scotch Brite','pct',12.90,4,'Pacote com 5.',true,'sponge,kitchen'),
('limpeza','Pano de Chão','Alvejante','pct',18.90,4,'Pacote com 5 unidades.',true,'cloth,floor'),
('limpeza','Pano Multiuso','Perfex','pct',14.90,4,'Rolo com 50 unidades.',true,'cloth,clean'),
('limpeza','Saco de Lixo 30L','Embalixo','pct',12.90,6,'Pacote com 30.',true,'trash,bag'),
('limpeza','Saco de Lixo 100L','Embalixo','pct',22.90,4,'Pacote com 30.',true,'trash,sack'),
('limpeza','Sabonete Líquido','Protex','gf',18.90,4,'Refil 500ml.',true,'hand,soap'),
('limpeza','Álcool 70%','Itajá','gf',12.90,6,'Garrafa 1L.',true,'alcohol,bottle'),
('limpeza','Álcool em Gel','Itajá','gf',18.90,4,'Frasco 500ml.',true,'gel,sanitizer'),
('limpeza','Papel Higiênico Folha Dupla','Neve','pct',28.90,4,'Pacote 12 rolos, 30m.',true,'toilet,paper'),
('limpeza','Papel Toalha','Snob','pct',14.90,4,'Pacote 2 rolos.',true,'paper,towel'),
('limpeza','Guardanapo de Papel','Mili','pct',5.90,12,'Pacote 50 folhas.',true,'napkin,paper'),
('limpeza','Lustra Inox','Bombril','gf',16.90,4,'Frasco 200ml.',true,'metal,polish'),
('limpeza','Tira Limo','Veja','gf',13.90,4,'Garrafa 500ml.',true,'cleaner,blue'),
('limpeza','Sabão para Louças','Limpol','gf',4.20,12,'Garrafa 500ml, coco.',true,'dish,soap'),
('limpeza','Detergente para Máquina','Finish','cx',38.90,2,'Caixa 30 tabletes.',true,'dishwasher,tab'),
('limpeza','Pastilha Sanitária','Pato','pct',9.90,6,'Pacote com 4.',true,'cleaner,toilet'),
('limpeza','Inseticida','SBP','gf',18.90,4,'Aerosol 300ml.',false,'insect,spray'),
('limpeza','Vassoura','Noviça','un',22.90,2,'Cabo plástico, cerdas macias.',true,'broom,clean'),
('limpeza','Rodo','Noviça','un',18.90,2,'Cabo 1.20m, base 40cm.',true,'squeegee'),
-- Embalagens
('embalagens','Marmita Alumínio N8','Wyda','pct',24.90,4,'Pacote com 100 unidades.',true,'foil,container'),
('embalagens','Marmita Alumínio N9','Wyda','pct',32.90,4,'Pacote com 100 unidades.',true,'aluminum,box'),
('embalagens','Marmita Isopor Quad','Termopack','pct',28.90,4,'Pacote 100 un, 750ml.',true,'foam,box'),
('embalagens','Caixa Pizza 35cm','Caixoteria','pct',78.90,2,'Pacote com 50 unidades.',true,'pizza,box'),
('embalagens','Caixa Pizza 25cm','Caixoteria','pct',58.90,2,'Pacote com 50 unidades.',true,'box,paper'),
('embalagens','Saco de Papel Kraft 5kg','Saqueira','pct',38.90,2,'Pacote com 100.',true,'paper,bag'),
('embalagens','Saco de Papel para Pão','Saqueira','pct',22.90,4,'Pacote com 500.',true,'bread,bag'),
('embalagens','Sacola Plástica Branca','Plastix','pct',28.90,4,'Pacote 1kg, 30x40cm.',true,'plastic,bag'),
('embalagens','Sacola Plástica Reciclada','Plastix','pct',32.90,4,'Pacote 1kg, 40x50cm.',true,'shopping,bag'),
('embalagens','Sacola Kraft','Saqueira','pct',58.90,2,'Pacote com 50, com alça.',true,'kraft,bag'),
('embalagens','Copo Descartável 200ml','Copobras','pct',6.90,6,'Pacote com 100.',true,'plastic,cup'),
('embalagens','Copo Descartável 50ml','Copobras','pct',4.90,6,'Pacote com 100, café.',true,'shot,cup'),
('embalagens','Copo Plástico Rígido 300ml','Plasutil','pct',14.90,4,'Pacote com 50.',true,'cup,clear'),
('embalagens','Prato Descartável 21cm','Copobras','pct',9.90,6,'Pacote com 10.',true,'plate,disposable'),
('embalagens','Prato de Papel','Copobras','pct',12.90,4,'Pacote com 10.',true,'paper,plate'),
('embalagens','Talher Descartável','Copobras','pct',18.90,4,'Pacote 100 mistos.',true,'cutlery,plastic'),
('embalagens','Canudo Descartável','Plastix','pct',6.90,6,'Pacote com 100.',true,'straw,plastic'),
('embalagens','Canudo de Papel','Plastix','pct',12.90,6,'Pacote com 100.',true,'straw,paper'),
('embalagens','Guardanapo de Papel','Mili','pct',5.90,12,'Pacote 50 folhas.',true,'napkin,white'),
('embalagens','Filme PVC 30cm','Wyda','rolo',9.90,4,'Rolo 30m.',true,'plastic,wrap'),
('embalagens','Filme PVC 40cm','Wyda','rolo',14.90,4,'Rolo 30m.',true,'plastic,roll'),
('embalagens','Papel Alumínio','Wyda','rolo',18.90,4,'Rolo 30cm x 7.5m.',true,'aluminum,foil'),
('embalagens','Papel Manteiga','Wyda','rolo',9.90,4,'Rolo 30cm x 5m.',true,'parchment,paper'),
('embalagens','Saquinho Plástico 1kg','Plastix','pct',18.90,4,'Pacote 1kg, transparente.',true,'plastic,small'),
('embalagens','Pote para Marmita 500ml','Termopack','pct',38.90,4,'Pacote com 100, com tampa.',true,'lunch,box'),
('embalagens','Pote para Marmita 1L','Termopack','pct',58.90,2,'Pacote com 100, com tampa.',true,'food,container'),
('embalagens','Etiqueta Adesiva','Pimaco','pct',22.90,4,'Pacote com 200, branca.',true,'label,paper'),
('embalagens','Saco Voal Decorativo','Saqueira','pct',14.90,4,'Pacote com 25.',true,'fabric,bag'),
('embalagens','Caixa Hambúrguer Kraft','Caixoteria','pct',38.90,2,'Pacote com 100.',true,'burger,box'),
('embalagens','Caixa Sushi','Caixoteria','pct',48.90,2,'Pacote com 50.',true,'sushi,box'),
('embalagens','Caixa Mini Cookie','Caixoteria','pct',22.90,4,'Pacote com 50.',true,'cookie,box'),
('embalagens','Bandeja Isopor','Termopack','pct',18.90,4,'Pacote com 100, M.',true,'foam,tray'),
('embalagens','Saco para Freezer 2kg','Plastix','pct',14.90,6,'Pacote com 100.',true,'freezer,bag'),
('embalagens','Sacola Boca de Palhaço','Plastix','pct',32.90,4,'Pacote 1kg, reforçada.',false,'plastic,reusable'),
('embalagens','Lacre Plástico','Plastix','pct',18.90,4,'Pacote com 100, autotravante.',true,'seal,strap'),
-- Doces
('doces','Chocolate ao Leite Tablete','Lacta','un',8.90,12,'Tablete 90g.',true,'chocolate,bar'),
('doces','Chocolate Branco','Nestlé','un',9.50,12,'Tablete 90g.',true,'white,chocolate'),
('doces','Chocolate 70% Cacau','Lindt','un',18.90,6,'Tablete 100g, importado.',true,'dark,chocolate'),
('doces','Chocolate Diet','Diet&Cia','un',12.90,6,'Tablete 80g.',true,'chocolate,square'),
('doces','Bombons Sortidos','Garoto','cx',28.90,4,'Caixa 250g.',true,'chocolate,box'),
('doces','Bombom Caju','Garoto','pct',12.90,6,'Pacote 200g.',true,'chocolate,nut'),
('doces','Trufa de Chocolate','Cacau Show','un',6.90,12,'Recheio cremoso.',true,'truffle'),
('doces','Pirulito Sortido','Bel','pct',9.90,6,'Pacote com 50.',true,'lollipop,bag'),
('doces','Bala de Goma','Fini','pct',12.90,6,'Pacote 500g, sortido.',true,'gummy,candy'),
('doces','Marshmallow','Doce Vida','pct',9.90,6,'Pacote 250g, branco.',true,'marshmallow'),
('doces','Jujuba','Florestal','pct',14.90,6,'Pacote 1kg, sortida.',true,'jelly,sweet'),
('doces','Chiclete','Trident','cx',4.90,12,'Caixa com 8 drágeas.',true,'gum,chewing'),
('doces','Bala de Mel','Hué','pct',8.90,6,'Pacote 500g.',true,'honey,candy'),
('doces','Caramelo Mole','Toffees','pct',12.90,6,'Pacote 500g.',true,'caramel,candy'),
('doces','Pastilha Hortelã','Halls','cx',3.90,24,'Caixa 28g.',true,'mint,candy'),
('doces','Pé de Moleque','Tradição','un',4.90,12,'Unidade 80g.',true,'peanut,brittle'),
('doces','Paçoquinha','Yoki','pct',14.90,4,'Pacote com 50 unidades.',true,'peanut,sweet'),
('doces','Cocada Branca','Tradição','un',5.90,12,'Unidade 80g.',true,'coconut,sweet'),
('doces','Cocada Queimada','Tradição','un',5.90,12,'Unidade 80g.',true,'coconut,brown'),
('doces','Doce de Abóbora','Tradição','pote',18.90,4,'Pote 600g.',true,'pumpkin,jam'),
('doces','Doce de Leite','Cremoso','pote',16.90,4,'Pote 600g.',true,'caramel,jar'),
('doces','Goiabada','Predilecta','cx',18.90,4,'Caixa 600g.',true,'guava,paste'),
('doces','Brigadeiro Gourmet','Doce Mel','cx',38.90,2,'Caixa com 12.',true,'truffle,box'),
('doces','Beijinho Gourmet','Doce Mel','cx',38.90,2,'Caixa com 12.',true,'coconut,gourmet'),
('doces','Gotas de Chocolate','Garoto','pct',18.90,4,'Pacote 500g.',true,'chocolate,chips'),
('doces','Granulado','Dori','pct',9.90,6,'Pacote 500g, colorido.',true,'sprinkles,colorful'),
('doces','Confeito Coloridos','Dori','pct',14.90,4,'Pacote 500g.',true,'candy,colored'),
('doces','Wafer Recheado','Bauducco','pct',7.90,6,'Pacote 100g, chocolate.',true,'wafer,biscuit'),
('doces','Biscoito Recheado','Trakinas','pct',4.90,12,'Pacote 145g, chocolate.',true,'cookie,filled'),
('doces','Biscoito de Chocolate','Negresco','pct',4.90,12,'Pacote 140g.',true,'cookie,oreo'),
('doces','Pipoca Doce','Pipoca Mais','pct',6.90,6,'Pacote 100g.',true,'popcorn,sweet'),
('doces','Algodão Doce','Doce Mel','pct',12.90,4,'Pacote 200g.',false,'cotton,candy'),
('doces','Bala de Coco','Florestal','pct',11.90,6,'Pacote 600g.',true,'coconut,bite'),
('doces','Chocolate Crocante','Lacta','un',9.90,12,'Tablete 90g, com flocos.',true,'chocolate,crunch'),
('doces','Bombom Recheado','Lacta','cx',22.90,4,'Caixa 24 unidades.',true,'chocolate,truffle'),
-- Congelados
('congelados','Pizza Mussarela','Sadia','un',22.90,4,'Pizza congelada 460g.',true,'pizza,cheese'),
('congelados','Pizza Calabresa','Sadia','un',22.90,4,'Pizza congelada 460g.',true,'pizza,frozen'),
('congelados','Pizza Quatro Queijos','Sadia','un',24.90,4,'Pizza congelada 480g.',true,'pizza,four,cheese'),
('congelados','Lasanha Bolonhesa','Seara','un',28.90,4,'Bandeja 600g.',true,'lasagna,frozen'),
('congelados','Lasanha Quatro Queijos','Sadia','un',28.90,4,'Bandeja 600g.',true,'lasagna,cheese'),
('congelados','Hambúrguer Bovino','Seara','pct',24.90,4,'Pacote 56 un de 56g.',true,'burger,frozen'),
('congelados','Hambúrguer Vegano','Fazenda Futuro','pct',28.90,4,'Pacote com 4 un.',true,'burger,plant'),
('congelados','Nuggets de Frango','Sadia','pct',18.90,6,'Pacote 1kg.',true,'nuggets,box'),
('congelados','Empanados de Frango','Sadia','pct',22.90,4,'Pacote 1kg, peito.',true,'chicken,breaded'),
('congelados','Steak de Frango','Sadia','pct',18.90,4,'Pacote 750g.',true,'chicken,steak'),
('congelados','Almôndegas Bovinas','Seara','pct',19.90,4,'Pacote 1kg.',true,'meatballs,frozen'),
('congelados','Salsicha','Sadia','pct',12.90,6,'Pacote 500g.',true,'sausage,frozen'),
('congelados','Linguiça Toscana Congelada','Aurora','pct',22.90,4,'Pacote 1kg.',true,'sausage,toscana'),
('congelados','Pão de Queijo Cru','Forno de Minas','pct',22.90,4,'Pacote 1kg.',true,'cheesebread,frozen'),
('congelados','Coxinha Congelada','Casa do Salgado','pct',28.90,2,'Pacote com 50 mini.',true,'coxinha,brazilian'),
('congelados','Esfiha Aberta Congelada','Casa do Salgado','pct',32.90,2,'Pacote com 50.',true,'esfiha,frozen'),
('congelados','Empada Frango','Casa do Salgado','pct',32.90,2,'Pacote com 24.',true,'empada,brazilian'),
('congelados','Pastel Crú Congelado','Massa Boa','pct',18.90,4,'Pacote com 25 discos.',true,'pastel,raw'),
('congelados','Batata Pré-frita','McCain','pct',24.90,4,'Pacote 2kg, palito.',true,'fries,frozen'),
('congelados','Batata Rústica','McCain','pct',22.90,4,'Pacote 2kg.',true,'potato,wedge'),
('congelados','Mandioca Congelada','Yoki','pct',14.90,6,'Pacote 1kg, descascada.',true,'cassava,frozen'),
('congelados','Polpa de Açaí','Petruz','pct',18.90,4,'Pacote 4x100g.',true,'acai,pulp'),
('congelados','Polpa de Maracujá','Maguary','pct',12.90,6,'Pacote 4x100g.',true,'passionfruit,pulp'),
('congelados','Polpa de Manga','Maguary','pct',12.90,6,'Pacote 4x100g.',true,'mango,pulp'),
('congelados','Camarão Cinza','Pescados Atlântico','pct',78.90,1,'Pacote 1kg, M.',false,'shrimp,frozen'),
('congelados','Filé de Tilápia','Copescal','pct',38.90,2,'Pacote 1kg.',true,'fish,fillet'),
('congelados','Filé de Salmão','Salmar','pct',89.90,1,'Pacote 500g.',true,'salmon,frozen'),
('congelados','Bacalhau Dessalgado','Riberalves','pct',78.90,1,'Pacote 500g.',true,'cod,fish'),
('congelados','Atum em Posta','Pescados Atlântico','pct',48.90,2,'Pacote 500g.',true,'tuna,steak'),
('congelados','Vegetais Congelados Mix','Hortz','pct',14.90,6,'Pacote 600g.',true,'vegetables,frozen'),
('congelados','Brócolis Congelado','Hortz','pct',12.90,6,'Pacote 500g.',true,'broccoli,frozen'),
('congelados','Sorvete Creme','Kibon','pote',24.90,4,'Pote 1.5L.',true,'icecream,vanilla'),
('congelados','Sorvete Chocolate','Kibon','pote',24.90,4,'Pote 1.5L.',true,'icecream,chocolate'),
('congelados','Sorvete Morango','Kibon','pote',24.90,4,'Pote 1.5L.',true,'icecream,strawberry'),
('congelados','Açaí Cremoso','Petruz','pote',22.90,4,'Pote 1L, com guaraná.',true,'acai,frozen'),
-- Cafés e Chás
('cafes','Café Espresso em Grãos','Melitta','pct',32.90,4,'Pacote 500g, blend italiano.',true,'coffee,beans'),
('cafes','Café Gourmet Moído','Pilão','pct',24.90,4,'Pacote 500g, gourmet.',true,'coffee,ground'),
('cafes','Café Tradicional Moído','Melitta','pct',18.90,6,'Pacote 500g.',true,'coffee,bag'),
('cafes','Café Extraforte','3 Corações','pct',19.90,6,'Pacote 500g.',true,'coffee,strong'),
('cafes','Café Descafeinado','Melitta','pct',28.90,4,'Pacote 250g.',true,'coffee,decaf'),
('cafes','Café Orgânico','Café Orfeu','pct',38.90,2,'Pacote 250g, microlote.',true,'coffee,organic'),
('cafes','Café em Cápsulas','L Or','cx',24.90,6,'Caixa 10 cápsulas, ristretto.',true,'coffee,capsule'),
('cafes','Café em Cápsulas Lungo','L Or','cx',24.90,6,'Caixa 10 cápsulas.',true,'capsule,coffee'),
('cafes','Café em Cápsulas Decaf','L Or','cx',26.90,4,'Caixa 10 cápsulas.',true,'decaf,capsule'),
('cafes','Café Solúvel','Nescafé','pote',18.90,4,'Pote 100g.',true,'instant,coffee'),
('cafes','Café Solúvel Premium','Nescafé Origens','pote',32.90,4,'Pote 100g, etíope.',true,'coffee,jar'),
('cafes','Cappuccino Pronto','3 Corações','pct',14.90,4,'Pacote 200g, com chocolate.',true,'cappuccino'),
('cafes','Mocha em Pó','Melitta','pct',18.90,4,'Pacote 200g.',true,'mocha,powder'),
('cafes','Filtro de Papel 102','Melitta','cx',8.90,6,'Caixa com 30.',true,'filter,coffee'),
('cafes','Filtro de Papel 103','Melitta','cx',9.90,6,'Caixa com 30.',true,'filter,paper'),
('cafes','Chá Verde Sachê','Twinings','cx',22.90,4,'Caixa com 25 sachês.',true,'green,tea,bag'),
('cafes','Chá Camomila','Leão','cx',8.90,6,'Caixa com 25 sachês.',true,'chamomile,tea'),
('cafes','Chá de Hibisco','Dr. Oetker','cx',12.90,4,'Caixa 15 sachês.',true,'hibiscus,tea'),
('cafes','Chá Boldo','Leão','cx',8.90,6,'Caixa com 25 sachês.',true,'tea,bag'),
('cafes','Chá Erva-doce','Leão','cx',8.90,6,'Caixa com 25 sachês.',true,'fennel,tea'),
('cafes','Chá Mate Natural','Leão','cx',9.90,6,'Caixa 250g, queimado.',true,'mate,tea'),
('cafes','Chá Preto Sachê','Twinings','cx',22.90,4,'Caixa com 25, English Breakfast.',true,'black,tea'),
('cafes','Chá Earl Grey','Twinings','cx',22.90,4,'Caixa com 25 sachês.',true,'earl,grey'),
('cafes','Erva Mate para Chimarrão','Barão','pct',18.90,4,'Pacote 1kg, tradicional.',true,'yerba,mate'),
('cafes','Erva Mate Tereré','Barão','pct',14.90,4,'Pacote 500g.',true,'yerba,terere'),
('cafes','Açúcar Demerara','Native','pct',12.90,6,'Pacote 1kg.',true,'sugar,brown'),
('cafes','Adoçante Líquido','Linea','gf',14.90,4,'Frasco 100ml.',true,'sweetener'),
('cafes','Mel de Abelha','Apis Vida','pote',22.90,4,'Pote 500g.',true,'honey,jar'),
('cafes','Canela em Pó','Kitano','pct',6.90,6,'Pacote 30g.',true,'cinnamon,powder'),
('cafes','Cacau em Pó','Garoto','lata',18.90,4,'Lata 200g, 100% cacau.',true,'cocoa,powder'),
('cafes','Leite Vegetal de Aveia','Nutty','cx',14.90,4,'Caixa 1L.',true,'oat,milk'),
('cafes','Leite Vegetal de Amêndoas','Nutty','cx',22.90,4,'Caixa 1L.',false,'almond,milk'),
('cafes','Xarope para Café','Monin','gf',38.90,2,'Garrafa 700ml, baunilha.',true,'syrup,coffee'),
('cafes','Cobertura Chocolate','Hersheys','gf',14.90,4,'Frasco 200g.',true,'chocolate,sauce'),
('cafes','Açúcar para Café','União','pct',8.90,6,'Caixa 100 sachês.',true,'sugar,packet'),
-- Pescados
('pescados','Salmão Fresco em Posta','Salmar','kg',119.90,1,'Posta de 200g, refrigerado.',true,'salmon,steak'),
('pescados','Salmão Fresco em Filé','Salmar','kg',129.90,1,'Filé sem espinha.',true,'salmon,fillet'),
('pescados','Atum Fresco','Atlântico','kg',98.90,1,'Posta de 200g, refrigerado.',true,'tuna,fresh'),
('pescados','Pescada Branca','Atlântico','kg',38.90,1,'Inteira eviscerada.',true,'fish,white'),
('pescados','Tilápia Filé','Copescal','kg',48.90,1,'Filé fresco, sem espinha.',true,'tilapia,fish'),
('pescados','Tilápia Inteira','Copescal','kg',28.90,1,'Inteira eviscerada.',true,'fish,whole'),
('pescados','Bacalhau do Porto','Riberalves','kg',178.90,1,'Salgado, importado.',true,'cod,fish'),
('pescados','Bacalhau Dessalgado','Riberalves','kg',148.90,1,'Pronto para uso.',true,'cod,fillet'),
('pescados','Camarão Médio','Pescados Atlântico','kg',78.90,1,'Cinza, com casca.',true,'shrimp,small'),
('pescados','Camarão Grande','Pescados Atlântico','kg',128.90,1,'Sete-barbas.',true,'shrimp,large'),
('pescados','Camarão Limpo','Pescados Atlântico','kg',158.90,1,'Sem casca, sem cabeça.',true,'shrimp,clean'),
('pescados','Lula Limpa','Pescados Atlântico','kg',68.90,1,'Anel, congelada.',true,'squid,seafood'),
('pescados','Polvo Inteiro','Pescados Atlântico','kg',98.90,1,'Importado, peça 1kg.',false,'octopus'),
('pescados','Mexilhão sem Concha','Pescados Atlântico','kg',38.90,1,'Embalagem 1kg.',true,'mussel,shell'),
('pescados','Marisco','Pescados Atlântico','kg',32.90,1,'Sem concha, congelado.',true,'clams,seafood'),
('pescados','Vieira','Pescados Atlântico','kg',138.90,1,'Importada, congelada.',true,'scallop,seafood'),
('pescados','Sardinha Fresca','Atlântico','kg',22.90,1,'Inteira, refrigerada.',true,'sardine,fresh'),
('pescados','Pintado em Posta','Pescados do Pantanal','kg',58.90,1,'Posta de 200g.',true,'fish,large'),
('pescados','Robalo Inteiro','Atlântico','kg',88.90,1,'Inteiro eviscerado.',true,'fish,whole'),
('pescados','Linguado em Filé','Atlântico','kg',88.90,1,'Filé fresco.',true,'fish,fillet'),
('pescados','Pacu','Pescados do Pantanal','kg',48.90,1,'Inteiro, eviscerado.',true,'fish,plate'),
('pescados','Tambaqui','Pescados do Pantanal','kg',52.90,1,'Inteiro, eviscerado.',true,'fish,grey'),
('pescados','Truta Inteira','Truticultura SP','kg',58.90,1,'Eviscerada, peso médio 400g.',true,'trout,fish'),
('pescados','Cação em Filé','Atlântico','kg',38.90,1,'Filé limpo.',true,'fish,grilled'),
('pescados','Merluza em Filé','Atlântico','kg',32.90,1,'Filé congelado.',true,'merluza,fish'),
('pescados','Anchova','Atlântico','kg',36.90,1,'Inteira, refrigerada.',true,'anchovy,fish'),
('pescados','Lagosta','Pescados Atlântico','kg',218.90,1,'Inteira, congelada.',false,'lobster,seafood'),
('pescados','Caranguejo Limpo','Pescados do Norte','kg',58.90,1,'Pronto para uso.',true,'crab,meat'),
('pescados','Casquinha de Siri','Pescados do Norte','cx',12.90,6,'Pronta para forno, 100g.',true,'crab,casquinha'),
('pescados','Sushi Combinado','Sushi & Cia','pct',89.90,1,'Combo 24 peças.',true,'sushi,combo'),
('pescados','Sashimi de Salmão','Sushi & Cia','pct',78.90,1,'15 fatias frescas.',true,'sashimi,salmon'),
('pescados','Hashi Descartável','Sushi & Cia','pct',14.90,4,'Pacote 100 pares.',true,'chopsticks'),
('pescados','Molho Shoyu','Sakura','gf',12.90,6,'Garrafa 500ml.',true,'soy,sauce'),
('pescados','Wasabi em Pasta','Sakura','gf',18.90,4,'Bisnaga 43g.',true,'wasabi,paste'),
('pescados','Gengibre em Conserva','Sakura','pote',14.90,4,'Pote 200g.',true,'ginger,pickled')
ON CONFLICT DO NOTHING;
