// data.js — Suppliers and products for the simulated ordering site.
// Mock B2B catalogue, pt-BR. Images use loremflickr with locked seeds so each
// product gets a stable thumbnail tied to its keyword.

(function () {
  // ── Helpers ─────────────────────────────────────────────────────────────
  // Image source: picsum.photos serves reliably; we use a stable seed per
  // product so each card keeps the same picture across reloads. The keyword
  // is preserved on the record (.keyword) for future use, but the URL itself
  // is seed-based for reliability.
  const img = (kw, seed) =>
    `https://picsum.photos/seed/${encodeURIComponent(kw)}-${seed}/320/320`;

  // Compact product spec → full record. Each spec is:
  //   [name, brand, unit, price, minOrder, imgKw, desc, inStock?]
  // inStock defaults to true; set false explicitly to mark out-of-stock.
  let __id = 0;
  const seedFor = (s) => {
    let h = 2166136261;
    for (let i = 0; i < s.length; i++) { h = (h ^ s.charCodeAt(i)) * 16777619 >>> 0; }
    return (h % 9000) + 1000;
  };
  const expand = (specs) => specs.map(([name, brand, unit, price, min, kw, desc, inStock]) => ({
    id: ++__id,
    name, brand, unit,
    price: Number(price.toFixed(2)),
    minOrder: min,
    description: desc,
    inStock: inStock !== false,
    image: img(kw, seedFor(name + brand)),
    keyword: kw,
  }));

  // ── Suppliers ───────────────────────────────────────────────────────────
  const suppliers = [
    {
      id: 'hortifruti',
      name: 'Hortifruti Verde Vale',
      tagline: 'Frutas, legumes e verduras direto do produtor',
      category: 'Hortifruti',
      whatsapp: '5511991111111',
      address: 'CEAGESP — Pavilhão MLP, Box 24',
      cnpj: '12.345.678/0001-01',
      hero: 'vegetables,market',
      products: expand([
        ['Banana Prata', 'Sítio Boa Vista', 'kg', 6.90, 5, 'banana', 'Cacho com pencas firmes, ponto de maduração regular.'],
        ['Maçã Fuji', 'Pomar Catarina', 'kg', 9.50, 3, 'apple,red', 'Cat. Extra, calibre 110-130, polpa crocante.'],
        ['Tomate Italiano', 'Sítio Boa Vista', 'kg', 7.80, 5, 'tomato', 'Para molho — polpa firme, baixa acidez.'],
        ['Alface Crespa', 'Verduras Frescas', 'un', 3.20, 10, 'lettuce', 'Pé inteiro, lavado e embalado a vácuo.'],
        ['Cenoura', 'Sítio Boa Vista', 'kg', 4.90, 5, 'carrot', 'Cat. comum, raiz limpa e sem rachaduras.'],
        ['Cebola Branca', 'Cebolas do Sul', 'kg', 5.40, 10, 'onion', 'Cat. 3, casca seca e firme.'],
        ['Batata Inglesa', 'Cooperativa Serrana', 'kg', 4.20, 10, 'potato', 'Lavada, cat. especial, embalagem 50kg.'],
        ['Limão Tahiti', 'Cítricos Norte', 'kg', 7.10, 3, 'lime', 'Casca lisa, alto rendimento de suco.'],
        ['Abacaxi Pérola', 'Frutas do Norte', 'un', 8.90, 5, 'pineapple', 'Doçura média, ideal para sucos e sobremesas.'],
        ['Mamão Formosa', 'Frutas do Norte', 'kg', 6.40, 3, 'papaya', 'Maduro, polpa rosada, casca lisa.'],
        ['Manga Palmer', 'Frutas do Norte', 'kg', 8.20, 3, 'mango', 'Cat. especial, ponto de maturação regular.'],
        ['Melancia', 'Frutas do Norte', 'kg', 3.50, 10, 'watermelon', 'Cat. especial, peso médio 8-12kg por unidade.'],
        ['Pepino Caipira', 'Verduras Frescas', 'kg', 5.80, 3, 'cucumber', 'Casca verde, sem manchas.'],
        ['Pimentão Vermelho', 'Verduras Frescas', 'kg', 9.90, 3, 'pepper,red', 'Cat. extra, polpa grossa.'],
        ['Couve Manteiga', 'Verduras Frescas', 'maço', 3.50, 10, 'kale', 'Maço com 12-15 folhas, lavado.'],
        ['Brócolis Ninja', 'Verduras Frescas', 'un', 6.20, 5, 'broccoli', 'Floretes compactos, talo curto.'],
        ['Espinafre', 'Verduras Frescas', 'maço', 4.50, 5, 'spinach', 'Folhas tenras, sem maço amarelado.'],
        ['Rúcula', 'Verduras Frescas', 'maço', 3.80, 10, 'arugula', 'Folhas pequenas, sabor acentuado.'],
        ['Salsinha', 'Verduras Frescas', 'maço', 2.40, 10, 'parsley', 'Maço fresco, lavado.'],
        ['Cebolinha', 'Verduras Frescas', 'maço', 2.40, 10, 'chives', 'Maço fresco, lavado.'],
        ['Beterraba', 'Sítio Boa Vista', 'kg', 5.10, 5, 'beetroot', 'Cat. extra, sem brotos.'],
        ['Abobrinha', 'Verduras Frescas', 'kg', 6.80, 3, 'zucchini', 'Cat. comum, casca lisa.'],
        ['Berinjela', 'Verduras Frescas', 'kg', 6.30, 3, 'eggplant', 'Polpa firme, brilho intenso.'],
        ['Chuchu', 'Sítio Boa Vista', 'kg', 4.10, 5, 'chayote', 'Cat. comum, polpa branca.'],
        ['Mandioquinha', 'Cooperativa Serrana', 'kg', 9.90, 3, 'parsnip', 'Cat. especial, sem fibras.'],
        ['Inhame', 'Sítio Boa Vista', 'kg', 7.20, 3, 'yam', 'Cat. comum, peso médio 0,5-1kg.'],
        ['Milho Verde', 'Cooperativa Serrana', 'dúzia', 12.00, 1, 'corn', 'Espigas frescas, grãos cheios.', false],
        ['Coentro', 'Verduras Frescas', 'maço', 2.80, 10, 'cilantro', 'Maço fresco, sem amarelados.'],
        ['Manjericão', 'Verduras Frescas', 'maço', 4.20, 5, 'basil', 'Folhas grandes, aroma intenso.'],
        ['Pera Williams', 'Pomar Catarina', 'kg', 12.50, 3, 'pear', 'Importada, polpa suculenta.'],
        ['Uva Itália', 'Vinhedos Sul', 'kg', 14.80, 2, 'grapes', 'Cacho compacto, sabor doce.'],
        ['Morango', 'Cooperativa Serrana', 'bdj', 7.90, 5, 'strawberry', 'Bandeja com 250g, fruta firme.'],
        ['Laranja Pera', 'Cítricos Norte', 'kg', 4.40, 10, 'orange', 'Para suco, alto rendimento.'],
        ['Mexerica Ponkan', 'Cítricos Norte', 'kg', 6.80, 5, 'mandarin,citrus', 'Cat. especial, doçura alta.'],
        ['Kiwi', 'Pomar Catarina', 'kg', 18.90, 1, 'kiwi', 'Importado do Chile, polpa firme.', false],
      ]),
    },
    {
      id: 'acougue',
      name: 'Açougue Boi Bom',
      tagline: 'Cortes nobres e diários para o food service',
      category: 'Açougue',
      whatsapp: '5511992222222',
      address: 'Av. das Carnes, 1240 — Vila Industrial',
      cnpj: '23.456.789/0001-02',
      hero: 'butcher,meat',
      products: expand([
        ['Picanha Bovina', 'Friboi', 'kg', 89.90, 1, 'picanha,beef', 'Peça inteira, capa de gordura padrão exportação.'],
        ['Alcatra', 'Friboi', 'kg', 54.90, 1, 'beef,steak', 'Peça inteira, marmoreio regular.'],
        ['Contrafilé', 'Friboi', 'kg', 62.50, 1, 'striploin,beef', 'Cat. especial, manta inteira.'],
        ['Filé Mignon', 'Marfrig', 'kg', 119.90, 0.5, 'filet,mignon', 'Peça limpa, sem cordão.'],
        ['Coxão Mole', 'Friboi', 'kg', 42.90, 1, 'beef,roast', 'Para bifes e estrogonofe.'],
        ['Coxão Duro', 'Friboi', 'kg', 38.90, 1, 'beef,roast', 'Para cozidos e moído.'],
        ['Patinho', 'Friboi', 'kg', 44.50, 1, 'beef,raw', 'Cat. extra, baixo teor de gordura.'],
        ['Acém', 'JBS', 'kg', 32.90, 1, 'beef,chuck', 'Para ensopados e moído.'],
        ['Costela Bovina', 'JBS', 'kg', 34.90, 2, 'beef,ribs', 'Tira fina, ideal para churrasco.'],
        ['Fraldinha', 'Friboi', 'kg', 48.90, 1, 'flank,steak', 'Manta inteira, fibras longas.'],
        ['Maminha', 'Friboi', 'kg', 56.90, 1, 'tri,tip,beef', 'Peça inteira, capa de gordura.'],
        ['Cupim', 'Marfrig', 'kg', 39.90, 1, 'cupim,brazilian,bbq', 'Peça inteira, ideal para assar.'],
        ['Carne Moída 2ª', 'Friboi', 'kg', 28.90, 2, 'ground,beef', 'Moída na hora, embalagem a vácuo.'],
        ['Músculo', 'Friboi', 'kg', 32.50, 1, 'beef,stew', 'Para sopas e cozidos longos.'],
        ['Língua Bovina', 'JBS', 'kg', 38.90, 1, 'tongue,beef', 'Limpa, embalada a vácuo.'],
        ['Coração de Frango', 'Sadia', 'kg', 24.90, 1, 'chicken,heart', 'Limpos, embalagem 1kg.'],
        ['Peito de Frango', 'Sadia', 'kg', 22.50, 2, 'chicken,breast', 'Sem osso, sem pele, embalagem 1kg.'],
        ['Coxa e Sobrecoxa', 'Sadia', 'kg', 16.90, 2, 'chicken,thigh', 'Resfriadas, com osso.'],
        ['Asa de Frango', 'Perdigão', 'kg', 18.90, 2, 'chicken,wings', 'Resfriadas, embalagem 1kg.'],
        ['Frango Inteiro', 'Sadia', 'kg', 14.90, 2, 'chicken,raw', 'Resfriado, peso médio 2kg.'],
        ['Linguiça Toscana', 'Aurora', 'kg', 26.90, 2, 'sausage,pork', 'Pura suína, embalagem 1kg.'],
        ['Linguiça Calabresa', 'Sadia', 'kg', 32.90, 1, 'pepperoni,sausage', 'Curada, ideal para pizzas.'],
        ['Bacon em Cubos', 'Sadia', 'kg', 38.90, 0.5, 'bacon', 'Cubos prontos para uso.'],
        ['Bacon em Manta', 'Sadia', 'kg', 42.50, 0.5, 'bacon,strips', 'Manta inteira, defumado.'],
        ['Costela Suína', 'Aurora', 'kg', 28.90, 2, 'pork,ribs', 'Tira inteira, ideal para assar.'],
        ['Pernil Suíno', 'Aurora', 'kg', 24.90, 2, 'pork,leg', 'Sem osso, peça inteira.'],
        ['Lombo Suíno', 'Aurora', 'kg', 26.90, 1, 'pork,loin', 'Peça inteira, baixa gordura.'],
        ['Salsicha Hot Dog', 'Sadia', 'pct', 12.90, 5, 'hotdog,sausage', 'Pacote 500g, 12 unidades.'],
        ['Hambúrguer Bovino', 'Seara', 'pct', 24.90, 5, 'hamburger,patty', 'Pacote com 56 unidades de 56g.'],
        ['Almôndegas', 'Seara', 'pct', 19.90, 3, 'meatballs', 'Bovinas congeladas, pacote 1kg.'],
        ['Costela de Cordeiro', 'Marfrig', 'kg', 89.90, 1, 'lamb,ribs', 'Importada do Uruguai.', false],
        ['Pernil de Cordeiro', 'Marfrig', 'kg', 78.90, 1, 'lamb,leg', 'Sem osso, peça inteira.', false],
        ['Maminha Suína', 'Aurora', 'kg', 22.90, 1, 'pork,raw', 'Cat. extra, com capa de gordura.'],
        ['Carré de Cordeiro', 'Marfrig', 'kg', 99.90, 1, 'rack,lamb', 'Francês, embalagem a vácuo.'],
        ['Carne Moída Especial', 'Friboi', 'kg', 36.90, 1, 'ground,beef', 'Patinho moído, baixa gordura.'],
      ]),
    },
    {
      id: 'laticinios',
      name: 'Laticínios Bela Vista',
      tagline: 'Queijos, leites e derivados frescos',
      category: 'Laticínios',
      whatsapp: '5511993333333',
      address: 'Estrada do Leite, km 12 — Zona Rural',
      cnpj: '34.567.890/0001-03',
      hero: 'cheese,dairy',
      products: expand([
        ['Leite Integral', 'Itambé', 'L', 5.90, 12, 'milk,carton', 'Caixa 1L, longa vida.'],
        ['Leite Desnatado', 'Itambé', 'L', 6.40, 12, 'milk,glass', 'Caixa 1L, zero gordura.'],
        ['Leite Semidesnatado', 'Piracanjuba', 'L', 6.10, 12, 'milk,bottle', 'Caixa 1L.'],
        ['Queijo Mussarela', 'Tirolez', 'kg', 42.90, 1, 'mozzarella,cheese', 'Peça inteira ou fatiada.'],
        ['Queijo Prato', 'Tirolez', 'kg', 44.90, 1, 'cheese,wheel', 'Peça padrão, fatias finas.'],
        ['Queijo Parmesão', 'Faixa Azul', 'kg', 78.90, 0.5, 'parmesan,cheese', 'Maturado 12 meses, ralado ou em cunha.'],
        ['Queijo Coalho', 'Vigor', 'kg', 48.90, 1, 'cheese,grilled', 'Espetinhos prontos, embalagem 500g.'],
        ['Queijo Minas Frescal', 'Tirolez', 'kg', 32.90, 1, 'cheese,fresh', 'Peça 500g, salgado leve.'],
        ['Requeijão', 'Catupiry', 'pote', 14.90, 6, 'cream,cheese', 'Pote 200g, original.'],
        ['Cream Cheese', 'Polenghi', 'pote', 18.90, 4, 'creamcheese', 'Pote 150g, tradicional.'],
        ['Manteiga sem Sal', 'Aviação', 'pct', 14.50, 6, 'butter', 'Tablete 200g, sem sal.'],
        ['Manteiga com Sal', 'Aviação', 'pct', 14.50, 6, 'butter,salt', 'Tablete 200g, com sal.'],
        ['Iogurte Natural', 'Vigor', 'L', 8.90, 6, 'yogurt', 'Pote 1L, sem açúcar.'],
        ['Iogurte de Morango', 'Danone', 'pct', 9.90, 4, 'yogurt,strawberry', 'Bandeja com 6 potes de 100g.'],
        ['Iogurte Grego', 'Vigor', 'pote', 7.90, 6, 'greek,yogurt', 'Pote 130g, tradicional.'],
        ['Creme de Leite UHT', 'Itambé', 'cx', 4.50, 12, 'cream,milk', 'Caixa 200g, longa vida.'],
        ['Leite Condensado', 'Moça', 'cx', 7.20, 12, 'condensed,milk', 'Caixa 395g.'],
        ['Leite em Pó Integral', 'Ninho', 'lata', 28.90, 4, 'powder,milk', 'Lata 400g, integral.'],
        ['Queijo Gorgonzola', 'Faixa Azul', 'kg', 89.90, 0.5, 'gorgonzola,cheese', 'Importado, peça 200g.', false],
        ['Queijo Provolone', 'Tirolez', 'kg', 64.90, 0.5, 'provolone,cheese', 'Peça defumada inteira.'],
        ['Queijo Brie', 'President', 'pct', 32.90, 2, 'brie,cheese', 'Peça 200g, importado da França.'],
        ['Queijo Camembert', 'President', 'pct', 32.90, 2, 'camembert,cheese', 'Peça 250g, importado.'],
        ['Ricota Fresca', 'Tirolez', 'kg', 28.90, 1, 'ricotta,cheese', 'Peça 500g, sem sal.'],
        ['Iogurte Desnatado', 'Vigor', 'L', 8.90, 6, 'yogurt,plain', 'Pote 1L, zero gordura.'],
        ['Doce de Leite', 'Mococa', 'pote', 16.90, 4, 'dulce,leche', 'Pote 600g, tradicional.'],
        ['Achocolatado em Pó', 'Nescau', 'pct', 14.90, 6, 'chocolate,powder', 'Pacote 400g, refil.'],
        ['Manteiga de Garrafa', 'Aviação', 'L', 38.90, 1, 'butter,oil', 'Garrafa 500ml, do sertão.'],
        ['Queijo Cottage', 'Vigor', 'pote', 12.90, 4, 'cottage,cheese', 'Pote 200g, baixa gordura.'],
        ['Queijo Reino', 'Polenghi', 'kg', 84.90, 0.5, 'cheese,red', 'Peça inteira, defumado.'],
        ['Queijo Canastra', 'Tirolez', 'kg', 92.90, 0.5, 'mountain,cheese', 'Mineiro artesanal, maturado 22 dias.', false],
        ['Iogurte Coalhada', 'Vigor', 'pote', 7.50, 6, 'yogurt', 'Pote 130g.'],
        ['Bebida Láctea', 'Itambé', 'L', 4.90, 6, 'milk,bottle', 'Pote 1kg, sabor morango.'],
        ['Queijo Mineiro Padrão', 'Tirolez', 'kg', 38.90, 1, 'cheese,white', 'Peça 700g, levemente salgado.'],
        ['Margarina', 'Qualy', 'pote', 12.90, 6, 'margarine', 'Pote 500g, com sal.'],
        ['Nata', 'Tirolez', 'pote', 14.90, 4, 'cream', 'Pote 300g, fresca.'],
      ]),
    },
    {
      id: 'padaria',
      name: 'Padaria Pão Quente',
      tagline: 'Pães, doces e salgados feitos hoje',
      category: 'Panificação',
      whatsapp: '5511994444444',
      address: 'Rua das Padarias, 88 — Centro',
      cnpj: '45.678.901/0001-04',
      hero: 'bread,bakery',
      products: expand([
        ['Pão Francês', 'Casa', 'kg', 18.90, 1, 'french,bread', 'Assado na hora, casca crocante.'],
        ['Pão de Forma', 'Wickbold', 'pct', 9.90, 6, 'sliced,bread', 'Pacote 500g, fatiado.'],
        ['Pão de Hambúrguer', 'Casa', 'pct', 14.90, 4, 'hamburger,bun', 'Pacote com 8 unidades.'],
        ['Pão de Hot Dog', 'Casa', 'pct', 14.90, 4, 'hotdog,bun', 'Pacote com 10 unidades.'],
        ['Pão Sírio', 'Casa', 'pct', 12.90, 4, 'pita,bread', 'Pacote com 6 unidades.'],
        ['Pão Italiano', 'Casa', 'un', 16.90, 4, 'italian,bread', 'Peça 500g, casca rústica.'],
        ['Pão Integral', 'Wickbold', 'pct', 11.90, 6, 'wholewheat,bread', 'Pacote 500g, fatiado.'],
        ['Pão Australiano', 'Casa', 'un', 18.90, 3, 'rye,bread', 'Peça 400g, com mel e malte.'],
        ['Pão de Queijo Cru', 'Forno de Minas', 'pct', 22.90, 3, 'cheese,bread', 'Congelado, pacote 1kg.'],
        ['Pão de Queijo Assado', 'Casa', 'kg', 38.90, 1, 'cheese,puff', 'Assado na hora.'],
        ['Coxinha de Frango', 'Casa', 'un', 7.90, 12, 'coxinha,brazilian', 'Recheio de frango desfiado.'],
        ['Esfiha de Carne', 'Casa', 'un', 6.50, 12, 'esfiha,middle,east', 'Massa fina, recheio temperado.'],
        ['Pastel de Queijo', 'Casa', 'un', 7.20, 12, 'pastel,fried', 'Massa frita, queijo derretido.'],
        ['Empada de Frango', 'Casa', 'un', 8.50, 6, 'empada,brazilian', 'Massa amanteigada, recheio cremoso.'],
        ['Quibe Frito', 'Casa', 'un', 7.90, 12, 'kibe,arabic', 'Recheio de carne moída.'],
        ['Pão de Cachorro Quente', 'Casa', 'pct', 13.50, 4, 'hotdog,brazilian', 'Pacote com 10.'],
        ['Bolo de Cenoura', 'Casa', 'un', 32.90, 1, 'carrot,cake', 'Bolo inteiro, cobertura de chocolate.'],
        ['Bolo de Fubá', 'Casa', 'un', 28.90, 1, 'cornmeal,cake', 'Receita tradicional.'],
        ['Bolo de Chocolate', 'Casa', 'un', 36.90, 1, 'chocolate,cake', 'Recheio e cobertura de brigadeiro.'],
        ['Brigadeiro', 'Casa', 'un', 4.50, 24, 'brigadeiro,sweet', 'Tradicional, granulado.'],
        ['Beijinho', 'Casa', 'un', 4.50, 24, 'coconut,sweet', 'Coco e cravo.'],
        ['Sonho', 'Casa', 'un', 8.90, 6, 'donut,cream', 'Recheio de creme, açúcar polvilhado.'],
        ['Croissant', 'Casa', 'un', 9.90, 6, 'croissant', 'Folhado amanteigado.'],
        ['Pão Doce', 'Casa', 'un', 5.90, 12, 'sweet,bun', 'Recheio de creme.'],
        ['Bisnaguinha', 'Pullman', 'pct', 7.90, 6, 'sweet,roll', 'Pacote 300g, doce e macia.'],
        ['Pão Sovado', 'Casa', 'un', 14.90, 4, 'sandwich,roll', 'Tipo cabocla, peça 500g.'],
        ['Torrada', 'Bauducco', 'pct', 8.90, 6, 'toast,bread', 'Pacote 160g, tradicional.'],
        ['Biscoito de Polvilho', 'Casa', 'pct', 9.90, 6, 'biscuit,white', 'Pacote 300g, doce.'],
        ['Empadão de Frango', 'Casa', 'un', 48.90, 1, 'empadao,pie', 'Forma 25cm, serve 8.'],
        ['Quiche Lorraine', 'Casa', 'un', 52.90, 1, 'quiche,bacon', 'Forma 22cm, com bacon e queijo.'],
        ['Salgados Mistos', 'Casa', 'cento', 280.00, 1, 'finger,food', 'Cento variado para festa.', false],
        ['Doces Mistos', 'Casa', 'cento', 220.00, 1, 'sweets,assorted', 'Cento variado para festa.'],
        ['Bolo Confeitado', 'Casa', 'un', 89.90, 1, 'cake,decorated', 'Forma 25cm, recheio à escolha.'],
        ['Pão Recheado', 'Casa', 'un', 24.90, 2, 'stuffed,bread', 'Recheio de presunto e queijo.'],
        ['Folhado de Frango', 'Casa', 'un', 8.90, 6, 'pastry,puff', 'Massa folhada, recheio cremoso.'],
      ]),
    },
    {
      id: 'mercearia',
      name: 'Mercearia do Bairro',
      tagline: 'Itens de prateleira para o dia a dia',
      category: 'Mercearia',
      whatsapp: '5511995555555',
      address: 'Av. Comercial, 555 — Bairro do Mercado',
      cnpj: '56.789.012/0001-05',
      hero: 'grocery,store',
      products: expand([
        ['Arroz Branco Tipo 1', 'Tio João', 'pct', 28.90, 5, 'rice,bag', 'Pacote 5kg, agulhinha.'],
        ['Feijão Carioca', 'Camil', 'pct', 9.90, 6, 'beans,brown', 'Pacote 1kg, tipo 1.'],
        ['Feijão Preto', 'Camil', 'pct', 10.50, 6, 'black,beans', 'Pacote 1kg.'],
        ['Açúcar Refinado', 'União', 'pct', 5.20, 12, 'sugar,white', 'Pacote 1kg.'],
        ['Açúcar Cristal', 'Caravelas', 'pct', 4.50, 12, 'sugar,cristal', 'Pacote 1kg.'],
        ['Sal Refinado', 'Cisne', 'pct', 3.40, 12, 'salt,white', 'Pacote 1kg.'],
        ['Óleo de Soja', 'Soya', 'cx', 8.90, 12, 'cooking,oil', 'Garrafa 900ml.'],
        ['Azeite Extra Virgem', 'Gallo', 'gl', 39.90, 4, 'olive,oil', 'Garrafa 500ml, importado.'],
        ['Vinagre de Maçã', 'Castelo', 'gl', 8.90, 6, 'apple,vinegar', 'Garrafa 750ml.'],
        ['Vinagre Branco', 'Castelo', 'gl', 4.90, 6, 'vinegar,bottle', 'Garrafa 750ml.'],
        ['Macarrão Espaguete', 'Barilla', 'pct', 6.90, 6, 'spaghetti,pasta', 'Pacote 500g, sêmola.'],
        ['Macarrão Penne', 'Barilla', 'pct', 6.90, 6, 'penne,pasta', 'Pacote 500g.'],
        ['Macarrão Parafuso', 'Adria', 'pct', 5.50, 6, 'pasta,fusilli', 'Pacote 500g.'],
        ['Molho de Tomate', 'Pomarola', 'cx', 4.20, 12, 'tomato,sauce', 'Caixa 340g, tradicional.'],
        ['Extrato de Tomate', 'Quero', 'lata', 4.90, 12, 'tomato,paste', 'Lata 340g.'],
        ['Farinha de Trigo', 'Dona Benta', 'pct', 6.90, 6, 'flour,wheat', 'Pacote 1kg.'],
        ['Farinha de Mandioca', 'Yoki', 'pct', 8.90, 4, 'flour,cassava', 'Pacote 500g, torrada.'],
        ['Farinha de Milho', 'Yoki', 'pct', 5.90, 4, 'cornmeal', 'Pacote 500g.'],
        ['Fubá', 'Sinhá', 'pct', 4.50, 6, 'corn,flour', 'Pacote 1kg, mimoso.'],
        ['Aveia em Flocos', 'Quaker', 'pct', 8.90, 4, 'oats,flake', 'Pacote 500g.'],
        ['Café Torrado e Moído', 'Pilão', 'pct', 18.90, 6, 'coffee,powder', 'Pacote 500g, tradicional.'],
        ['Café em Grãos', 'Melitta', 'pct', 28.90, 4, 'coffee,bean', 'Pacote 500g, espresso.'],
        ['Achocolatado em Pó', 'Nescau', 'pct', 14.90, 6, 'cocoa,powder', 'Pacote 400g.'],
        ['Maionese', 'Hellmanns', 'pote', 14.90, 6, 'mayonnaise,jar', 'Pote 500g.'],
        ['Catchup', 'Heinz', 'gl', 12.90, 6, 'ketchup,bottle', 'Bisnaga 397g.'],
        ['Mostarda', 'Heinz', 'gl', 10.90, 6, 'mustard,bottle', 'Bisnaga 200g.'],
        ['Molho Inglês', 'Lea Perrins', 'gl', 18.90, 4, 'sauce,bottle', 'Garrafa 150ml.'],
        ['Tempero Pronto', 'Sazón', 'cx', 4.90, 12, 'spice,box', 'Caixa 60g, completo.'],
        ['Caldo em Tablete', 'Knorr', 'cx', 5.90, 12, 'bouillon,cube', 'Caixa com 6 cubos.'],
        ['Lentilha', 'Camil', 'pct', 12.90, 4, 'lentils,brown', 'Pacote 500g.'],
        ['Grão de Bico', 'Camil', 'pct', 14.90, 4, 'chickpeas', 'Pacote 500g.'],
        ['Ervilha em Conserva', 'Quero', 'lata', 5.90, 12, 'peas,canned', 'Lata 200g.'],
        ['Milho em Conserva', 'Quero', 'lata', 5.90, 12, 'corn,canned', 'Lata 200g.'],
        ['Atum Sólido', 'Gomes da Costa', 'lata', 14.90, 6, 'tuna,canned', 'Lata 170g, em água e sal.'],
        ['Sardinha em Óleo', 'Coqueiro', 'lata', 9.90, 6, 'sardine,canned', 'Lata 125g.', false],
      ]),
    },
    {
      id: 'bebidas',
      name: 'Bebidas Refresca',
      tagline: 'Refrigerantes, sucos, águas e energéticos',
      category: 'Bebidas',
      whatsapp: '5511996666666',
      address: 'Rod. dos Bandeirantes, km 35 — CD Bebidas',
      cnpj: '67.890.123/0001-06',
      hero: 'beverage,drinks',
      products: expand([
        ['Refrigerante Cola 2L', 'Marca Cola', 'gf', 9.90, 6, 'soda,bottle', 'Garrafa 2L, regular.'],
        ['Refrigerante Cola Lata', 'Marca Cola', 'lata', 4.90, 12, 'soda,can', 'Lata 350ml.'],
        ['Refrigerante Guaraná 2L', 'Marca Guaraná', 'gf', 8.90, 6, 'guarana,soda', 'Garrafa 2L.'],
        ['Refrigerante Laranja', 'Marca Laranja', 'gf', 8.50, 6, 'orange,soda', 'Garrafa 2L.'],
        ['Refrigerante Limão', 'Marca Limão', 'gf', 8.50, 6, 'lemon,soda', 'Garrafa 2L.'],
        ['Refrigerante Uva', 'Marca Uva', 'gf', 7.90, 6, 'grape,soda', 'Garrafa 2L.'],
        ['Água Mineral 500ml', 'Crystal', 'pct', 14.90, 4, 'mineral,water', 'Fardo com 12 garrafas.'],
        ['Água Mineral 1.5L', 'Crystal', 'gf', 4.50, 6, 'water,bottle', 'Garrafa 1.5L sem gás.'],
        ['Água com Gás', 'Crystal', 'gf', 4.90, 6, 'sparkling,water', 'Garrafa 500ml.'],
        ['Suco de Laranja', 'Del Valle', 'cx', 8.90, 6, 'orange,juice', 'Caixa 1L, néctar.'],
        ['Suco de Uva Integral', 'Aurora', 'gf', 22.90, 4, 'grape,juice', 'Garrafa 1.5L, sem açúcar.'],
        ['Suco de Maçã', 'Del Valle', 'cx', 8.90, 6, 'apple,juice', 'Caixa 1L.'],
        ['Suco de Pêssego', 'Del Valle', 'cx', 8.90, 6, 'peach,juice', 'Caixa 1L.'],
        ['Néctar de Goiaba', 'Maguary', 'cx', 7.90, 6, 'guava,juice', 'Caixa 1L.'],
        ['Chá Mate Gelado', 'Leão', 'gf', 6.90, 6, 'iced,tea', 'Garrafa 1.5L, natural.'],
        ['Chá Verde Gelado', 'Leão', 'gf', 7.50, 6, 'green,tea', 'Garrafa 1.5L.'],
        ['Energético 2L', 'Marca Energy', 'gf', 22.90, 4, 'energy,drink', 'Garrafa 2L.'],
        ['Energético Lata', 'Marca Energy', 'lata', 9.90, 12, 'energy,can', 'Lata 269ml.'],
        ['Isotônico Limão', 'Gatorade', 'gf', 7.90, 6, 'sports,drink', 'Garrafa 500ml.'],
        ['Isotônico Tangerina', 'Gatorade', 'gf', 7.90, 6, 'sports,drink', 'Garrafa 500ml.'],
        ['Água de Coco', 'Kero Coco', 'cx', 9.90, 6, 'coconut,water', 'Caixa 1L, integral.'],
        ['Leite de Coco', 'Sococo', 'gf', 8.90, 6, 'coconut,milk', 'Garrafa 200ml.'],
        ['Cerveja Pilsen Long Neck', 'Marca Beer', 'pct', 78.90, 2, 'beer,longneck', 'Pack com 12 unidades, 355ml.', false],
        ['Cerveja Lata 350ml', 'Marca Beer', 'pct', 64.90, 2, 'beer,can', 'Fardo com 12 latas.', false],
        ['Refresco em Pó', 'Tang', 'cx', 1.90, 24, 'powder,drink', 'Sachê 25g, vários sabores.'],
        ['Xarope para Drink', 'Monin', 'gf', 38.90, 2, 'syrup,bottle', 'Garrafa 700ml, sabor caramelo.'],
        ['Xarope de Groselha', 'Milani', 'gf', 14.90, 4, 'syrup,red', 'Garrafa 900ml.'],
        ['Soda Limonada', 'Antarctica', 'gf', 6.90, 6, 'lemonade,soda', 'Garrafa 2L.'],
        ['Tônica', 'Schweppes', 'lata', 5.90, 12, 'tonic,water', 'Lata 350ml.'],
        ['Suco em Pó Maracujá', 'Maguary', 'cx', 1.90, 24, 'passionfruit,powder', 'Sachê 25g.'],
        ['Café Gelado', 'Nescafé', 'gf', 8.90, 6, 'iced,coffee', 'Garrafa 270ml.'],
        ['Coquetel Não Alcoólico', 'Vibe', 'gf', 12.90, 6, 'cocktail', 'Garrafa 275ml, mojito.'],
        ['Refresco de Caju', 'Maguary', 'cx', 9.90, 6, 'cashew,juice', 'Caixa 1L.'],
        ['Açaí Polpa', 'Petruz', 'pct', 18.90, 4, 'acai,bowl', 'Pacote 4x100g, congelado.'],
        ['Chá Camomila', 'Leão', 'cx', 8.90, 4, 'tea,bag', 'Caixa com 25 sachês.'],
      ]),
    },
    {
      id: 'limpeza',
      name: 'Limpeza Brilho Total',
      tagline: 'Higiene e limpeza profissional',
      category: 'Limpeza',
      whatsapp: '5511997777777',
      address: 'Rua Industrial, 100 — Galpão 5',
      cnpj: '78.901.234/0001-07',
      hero: 'cleaning,products',
      products: expand([
        ['Detergente Líquido', 'Ypê', 'gf', 3.90, 12, 'detergent,bottle', 'Garrafa 500ml, neutro.'],
        ['Detergente em Pó', 'Omo', 'cx', 32.90, 4, 'powder,detergent', 'Caixa 2kg, multiação.'],
        ['Sabão em Barra', 'Ypê', 'pct', 9.90, 6, 'soap,bar', 'Pacote com 5 unidades.'],
        ['Sabão Líquido para Roupas', 'Omo', 'gf', 28.90, 4, 'liquid,soap', 'Garrafa 3L, concentrado.'],
        ['Amaciante de Roupas', 'Comfort', 'gf', 22.90, 4, 'fabric,softener', 'Garrafa 2L, lavanda.'],
        ['Água Sanitária', 'Qboa', 'gf', 5.90, 6, 'bleach,bottle', 'Garrafa 1L.'],
        ['Cloro Concentrado', 'Sanigran', 'gf', 14.90, 4, 'bleach,gallon', 'Galão 5L.'],
        ['Multiuso', 'Veja', 'gf', 9.90, 6, 'spray,bottle', 'Spray 500ml.'],
        ['Limpa Vidros', 'Veja Vidrex', 'gf', 11.90, 6, 'glass,cleaner', 'Spray 500ml.'],
        ['Desinfetante Pinho', 'Pinho Sol', 'gf', 12.90, 6, 'disinfectant', 'Garrafa 500ml.'],
        ['Desinfetante Lavanda', 'Veja', 'gf', 12.90, 6, 'lavender,bottle', 'Garrafa 1L.'],
        ['Limpador de Piso', 'Veja', 'gf', 8.90, 6, 'floor,cleaner', 'Garrafa 750ml.'],
        ['Cera para Piso', 'Cera Mais', 'lata', 16.90, 4, 'wax,can', 'Lata 750ml, incolor.'],
        ['Lustra Móveis', 'Poliflor', 'gf', 14.90, 4, 'furniture,polish', 'Aerosol 200ml.'],
        ['Removedor de Manchas', 'Vanish', 'gf', 22.90, 4, 'stain,remover', 'Pó 450g.'],
        ['Esponja de Aço', 'Bombril', 'pct', 8.90, 6, 'steel,wool', 'Pacote com 8.'],
        ['Esponja Dupla Face', 'Scotch Brite', 'pct', 12.90, 4, 'sponge,kitchen', 'Pacote com 5.'],
        ['Pano de Chão', 'Alvejante', 'pct', 18.90, 4, 'cloth,floor', 'Pacote com 5 unidades.'],
        ['Pano Multiuso', 'Perfex', 'pct', 14.90, 4, 'cloth,clean', 'Rolo com 50 unidades.'],
        ['Saco de Lixo 30L', 'Embalixo', 'pct', 12.90, 6, 'trash,bag', 'Pacote com 30.'],
        ['Saco de Lixo 100L', 'Embalixo', 'pct', 22.90, 4, 'trash,sack', 'Pacote com 30.'],
        ['Sabonete Líquido', 'Protex', 'gf', 18.90, 4, 'hand,soap', 'Refil 500ml.'],
        ['Álcool 70%', 'Itajá', 'gf', 12.90, 6, 'alcohol,bottle', 'Garrafa 1L.'],
        ['Álcool em Gel', 'Itajá', 'gf', 18.90, 4, 'gel,sanitizer', 'Frasco 500ml.'],
        ['Papel Higiênico Folha Dupla', 'Neve', 'pct', 28.90, 4, 'toilet,paper', 'Pacote 12 rolos, 30m.'],
        ['Papel Toalha', 'Snob', 'pct', 14.90, 4, 'paper,towel', 'Pacote 2 rolos.'],
        ['Guardanapo de Papel', 'Mili', 'pct', 5.90, 12, 'napkin,paper', 'Pacote 50 folhas.'],
        ['Lustra Inox', 'Bombril', 'gf', 16.90, 4, 'metal,polish', 'Frasco 200ml.'],
        ['Tira Limo', 'Veja', 'gf', 13.90, 4, 'cleaner,blue', 'Garrafa 500ml.'],
        ['Sabão para Louças', 'Limpol', 'gf', 4.20, 12, 'dish,soap', 'Garrafa 500ml, coco.'],
        ['Detergente para Máquina', 'Finish', 'cx', 38.90, 2, 'dishwasher,tab', 'Caixa 30 tabletes.'],
        ['Pastilha Sanitária', 'Pato', 'pct', 9.90, 6, 'cleaner,toilet', 'Pacote com 4.'],
        ['Inseticida', 'SBP', 'gf', 18.90, 4, 'insect,spray', 'Aerosol 300ml.', false],
        ['Vassoura', 'Noviça', 'un', 22.90, 2, 'broom,clean', 'Cabo plástico, cerdas macias.'],
        ['Rodo', 'Noviça', 'un', 18.90, 2, 'squeegee', 'Cabo 1.20m, base 40cm.'],
      ]),
    },
    {
      id: 'embalagens',
      name: 'Embalagens Pratika',
      tagline: 'Embalagens, descartáveis e sacolas',
      category: 'Embalagens',
      whatsapp: '5511998888888',
      address: 'Rua dos Plásticos, 240 — Distrito Industrial',
      cnpj: '89.012.345/0001-08',
      hero: 'packaging,boxes',
      products: expand([
        ['Marmita Alumínio N8', 'Wyda', 'pct', 24.90, 4, 'foil,container', 'Pacote com 100 unidades.'],
        ['Marmita Alumínio N9', 'Wyda', 'pct', 32.90, 4, 'aluminum,box', 'Pacote com 100 unidades.'],
        ['Marmita Isopor Quad', 'Termopack', 'pct', 28.90, 4, 'foam,box', 'Pacote 100 un, 750ml.'],
        ['Caixa Pizza 35cm', 'Caixoteria', 'pct', 78.90, 2, 'pizza,box', 'Pacote com 50 unidades.'],
        ['Caixa Pizza 25cm', 'Caixoteria', 'pct', 58.90, 2, 'box,paper', 'Pacote com 50 unidades.'],
        ['Saco de Papel Kraft 5kg', 'Saqueira', 'pct', 38.90, 2, 'paper,bag', 'Pacote com 100.'],
        ['Saco de Papel para Pão', 'Saqueira', 'pct', 22.90, 4, 'bread,bag', 'Pacote com 500.'],
        ['Sacola Plástica Branca', 'Plastix', 'pct', 28.90, 4, 'plastic,bag', 'Pacote 1kg, 30x40cm.'],
        ['Sacola Plástica Reciclada', 'Plastix', 'pct', 32.90, 4, 'shopping,bag', 'Pacote 1kg, 40x50cm.'],
        ['Sacola Kraft', 'Saqueira', 'pct', 58.90, 2, 'kraft,bag', 'Pacote com 50, com alça.'],
        ['Copo Descartável 200ml', 'Copobras', 'pct', 6.90, 6, 'plastic,cup', 'Pacote com 100.'],
        ['Copo Descartável 50ml', 'Copobras', 'pct', 4.90, 6, 'shot,cup', 'Pacote com 100, café.'],
        ['Copo Plástico Rígido 300ml', 'Plasutil', 'pct', 14.90, 4, 'cup,clear', 'Pacote com 50.'],
        ['Prato Descartável 21cm', 'Copobras', 'pct', 9.90, 6, 'plate,disposable', 'Pacote com 10.'],
        ['Prato de Papel', 'Copobras', 'pct', 12.90, 4, 'paper,plate', 'Pacote com 10.'],
        ['Talher Descartável', 'Copobras', 'pct', 18.90, 4, 'cutlery,plastic', 'Pacote 100 mistos.'],
        ['Canudo Descartável', 'Plastix', 'pct', 6.90, 6, 'straw,plastic', 'Pacote com 100.'],
        ['Canudo de Papel', 'Plastix', 'pct', 12.90, 6, 'straw,paper', 'Pacote com 100.'],
        ['Guardanapo de Papel', 'Mili', 'pct', 5.90, 12, 'napkin,white', 'Pacote 50 folhas.'],
        ['Filme PVC 30cm', 'Wyda', 'rolo', 9.90, 4, 'plastic,wrap', 'Rolo 30m.'],
        ['Filme PVC 40cm', 'Wyda', 'rolo', 14.90, 4, 'plastic,roll', 'Rolo 30m.'],
        ['Papel Alumínio', 'Wyda', 'rolo', 18.90, 4, 'aluminum,foil', 'Rolo 30cm x 7.5m.'],
        ['Papel Manteiga', 'Wyda', 'rolo', 9.90, 4, 'parchment,paper', 'Rolo 30cm x 5m.'],
        ['Saquinho Plástico 1kg', 'Plastix', 'pct', 18.90, 4, 'plastic,small', 'Pacote 1kg, transparente.'],
        ['Pote para Marmita 500ml', 'Termopack', 'pct', 38.90, 4, 'lunch,box', 'Pacote com 100, com tampa.'],
        ['Pote para Marmita 1L', 'Termopack', 'pct', 58.90, 2, 'food,container', 'Pacote com 100, com tampa.'],
        ['Etiqueta Adesiva', 'Pimaco', 'pct', 22.90, 4, 'label,paper', 'Pacote com 200, branca.'],
        ['Saco Voal Decorativo', 'Saqueira', 'pct', 14.90, 4, 'fabric,bag', 'Pacote com 25.'],
        ['Caixa Hambúrguer Kraft', 'Caixoteria', 'pct', 38.90, 2, 'burger,box', 'Pacote com 100.'],
        ['Caixa Sushi', 'Caixoteria', 'pct', 48.90, 2, 'sushi,box', 'Pacote com 50.'],
        ['Caixa Mini Cookie', 'Caixoteria', 'pct', 22.90, 4, 'cookie,box', 'Pacote com 50.'],
        ['Bandeja Isopor', 'Termopack', 'pct', 18.90, 4, 'foam,tray', 'Pacote com 100, M.'],
        ['Saco para Freezer 2kg', 'Plastix', 'pct', 14.90, 6, 'freezer,bag', 'Pacote com 100.'],
        ['Sacola Boca de Palhaço', 'Plastix', 'pct', 32.90, 4, 'plastic,reusable', 'Pacote 1kg, reforçada.', false],
        ['Lacre Plástico', 'Plastix', 'pct', 18.90, 4, 'seal,strap', 'Pacote com 100, autotravante.'],
      ]),
    },
    {
      id: 'doces',
      name: 'Doce Mel',
      tagline: 'Balas, chocolates e confeitos',
      category: 'Doces',
      whatsapp: '5511999999999',
      address: 'Rua das Confeitarias, 78',
      cnpj: '90.123.456/0001-09',
      hero: 'candy,sweets',
      products: expand([
        ['Chocolate ao Leite Tablete', 'Lacta', 'un', 8.90, 12, 'chocolate,bar', 'Tablete 90g.'],
        ['Chocolate Branco', 'Nestlé', 'un', 9.50, 12, 'white,chocolate', 'Tablete 90g.'],
        ['Chocolate 70% Cacau', 'Lindt', 'un', 18.90, 6, 'dark,chocolate', 'Tablete 100g, importado.'],
        ['Chocolate Diet', 'Diet&Cia', 'un', 12.90, 6, 'chocolate,square', 'Tablete 80g.'],
        ['Bombons Sortidos', 'Garoto', 'cx', 28.90, 4, 'chocolate,box', 'Caixa 250g.'],
        ['Bombom Caju', 'Garoto', 'pct', 12.90, 6, 'chocolate,nut', 'Pacote 200g.'],
        ['Trufa de Chocolate', 'Cacau Show', 'un', 6.90, 12, 'truffle', 'Recheio cremoso.'],
        ['Pirulito Sortido', 'Bel', 'pct', 9.90, 6, 'lollipop,bag', 'Pacote com 50.'],
        ['Bala de Goma', 'Fini', 'pct', 12.90, 6, 'gummy,candy', 'Pacote 500g, sortido.'],
        ['Marshmallow', 'Doce Vida', 'pct', 9.90, 6, 'marshmallow', 'Pacote 250g, branco.'],
        ['Jujuba', 'Florestal', 'pct', 14.90, 6, 'jelly,sweet', 'Pacote 1kg, sortida.'],
        ['Chiclete', 'Trident', 'cx', 4.90, 12, 'gum,chewing', 'Caixa com 8 drágeas.'],
        ['Bala de Mel', 'Hué', 'pct', 8.90, 6, 'honey,candy', 'Pacote 500g.'],
        ['Caramelo Mole', 'Toffees', 'pct', 12.90, 6, 'caramel,candy', 'Pacote 500g.'],
        ['Pastilha Hortelã', 'Halls', 'cx', 3.90, 24, 'mint,candy', 'Caixa 28g.'],
        ['Pé de Moleque', 'Tradição', 'un', 4.90, 12, 'peanut,brittle', 'Unidade 80g.'],
        ['Paçoquinha', 'Yoki', 'pct', 14.90, 4, 'peanut,sweet', 'Pacote com 50 unidades.'],
        ['Cocada Branca', 'Tradição', 'un', 5.90, 12, 'coconut,sweet', 'Unidade 80g.'],
        ['Cocada Queimada', 'Tradição', 'un', 5.90, 12, 'coconut,brown', 'Unidade 80g.'],
        ['Doce de Abóbora', 'Tradição', 'pote', 18.90, 4, 'pumpkin,jam', 'Pote 600g.'],
        ['Doce de Leite', 'Cremoso', 'pote', 16.90, 4, 'caramel,jar', 'Pote 600g.'],
        ['Goiabada', 'Predilecta', 'cx', 18.90, 4, 'guava,paste', 'Caixa 600g.'],
        ['Brigadeiro Gourmet', 'Doce Mel', 'cx', 38.90, 2, 'truffle,box', 'Caixa com 12.'],
        ['Beijinho Gourmet', 'Doce Mel', 'cx', 38.90, 2, 'coconut,gourmet', 'Caixa com 12.'],
        ['Gotas de Chocolate', 'Garoto', 'pct', 18.90, 4, 'chocolate,chips', 'Pacote 500g.'],
        ['Granulado', 'Dori', 'pct', 9.90, 6, 'sprinkles,colorful', 'Pacote 500g, colorido.'],
        ['Confeito Coloridos', 'Dori', 'pct', 14.90, 4, 'candy,colored', 'Pacote 500g.'],
        ['Wafer Recheado', 'Bauducco', 'pct', 7.90, 6, 'wafer,biscuit', 'Pacote 100g, chocolate.'],
        ['Biscoito Recheado', 'Trakinas', 'pct', 4.90, 12, 'cookie,filled', 'Pacote 145g, chocolate.'],
        ['Biscoito de Chocolate', 'Negresco', 'pct', 4.90, 12, 'cookie,oreo', 'Pacote 140g.'],
        ['Pipoca Doce', 'Pipoca Mais', 'pct', 6.90, 6, 'popcorn,sweet', 'Pacote 100g.'],
        ['Algodão Doce', 'Doce Mel', 'pct', 12.90, 4, 'cotton,candy', 'Pacote 200g.', false],
        ['Bala de Coco', 'Florestal', 'pct', 11.90, 6, 'coconut,bite', 'Pacote 600g.'],
        ['Chocolate Crocante', 'Lacta', 'un', 9.90, 12, 'chocolate,crunch', 'Tablete 90g, com flocos.'],
        ['Bombom Recheado', 'Lacta', 'cx', 22.90, 4, 'chocolate,truffle', 'Caixa 24 unidades.'],
      ]),
    },
    {
      id: 'congelados',
      name: 'Congelados Antártida',
      tagline: 'Praticidade e qualidade no freezer',
      category: 'Congelados',
      whatsapp: '5511990000001',
      address: 'Rua do Frio, 200 — Galpão 2',
      cnpj: '01.234.567/0001-10',
      hero: 'frozen,food',
      products: expand([
        ['Pizza Mussarela', 'Sadia', 'un', 22.90, 4, 'pizza,cheese', 'Pizza congelada 460g.'],
        ['Pizza Calabresa', 'Sadia', 'un', 22.90, 4, 'pizza,frozen', 'Pizza congelada 460g.'],
        ['Pizza Quatro Queijos', 'Sadia', 'un', 24.90, 4, 'pizza,four,cheese', 'Pizza congelada 480g.'],
        ['Lasanha Bolonhesa', 'Seara', 'un', 28.90, 4, 'lasagna,frozen', 'Bandeja 600g.'],
        ['Lasanha Quatro Queijos', 'Sadia', 'un', 28.90, 4, 'lasagna,cheese', 'Bandeja 600g.'],
        ['Hambúrguer Bovino', 'Seara', 'pct', 24.90, 4, 'burger,frozen', 'Pacote 56 un de 56g.'],
        ['Hambúrguer Vegano', 'Fazenda Futuro', 'pct', 28.90, 4, 'burger,plant', 'Pacote com 4 un.'],
        ['Nuggets de Frango', 'Sadia', 'pct', 18.90, 6, 'nuggets,box', 'Pacote 1kg.'],
        ['Empanados de Frango', 'Sadia', 'pct', 22.90, 4, 'chicken,breaded', 'Pacote 1kg, peito.'],
        ['Steak de Frango', 'Sadia', 'pct', 18.90, 4, 'chicken,steak', 'Pacote 750g.'],
        ['Almôndegas Bovinas', 'Seara', 'pct', 19.90, 4, 'meatballs,frozen', 'Pacote 1kg.'],
        ['Salsicha', 'Sadia', 'pct', 12.90, 6, 'sausage,frozen', 'Pacote 500g.'],
        ['Linguiça Toscana Congelada', 'Aurora', 'pct', 22.90, 4, 'sausage,toscana', 'Pacote 1kg.'],
        ['Pão de Queijo Cru', 'Forno de Minas', 'pct', 22.90, 4, 'cheesebread,frozen', 'Pacote 1kg.'],
        ['Coxinha Congelada', 'Casa do Salgado', 'pct', 28.90, 2, 'coxinha,brazilian', 'Pacote com 50 mini.'],
        ['Esfiha Aberta Congelada', 'Casa do Salgado', 'pct', 32.90, 2, 'esfiha,frozen', 'Pacote com 50.'],
        ['Empada Frango', 'Casa do Salgado', 'pct', 32.90, 2, 'empada,brazilian', 'Pacote com 24.'],
        ['Pastel Crú Congelado', 'Massa Boa', 'pct', 18.90, 4, 'pastel,raw', 'Pacote com 25 discos.'],
        ['Batata Pré-frita', 'McCain', 'pct', 24.90, 4, 'fries,frozen', 'Pacote 2kg, palito.'],
        ['Batata Rústica', 'McCain', 'pct', 22.90, 4, 'potato,wedge', 'Pacote 2kg.'],
        ['Mandioca Congelada', 'Yoki', 'pct', 14.90, 6, 'cassava,frozen', 'Pacote 1kg, descascada.'],
        ['Polpa de Açaí', 'Petruz', 'pct', 18.90, 4, 'acai,pulp', 'Pacote 4x100g.'],
        ['Polpa de Maracujá', 'Maguary', 'pct', 12.90, 6, 'passionfruit,pulp', 'Pacote 4x100g.'],
        ['Polpa de Manga', 'Maguary', 'pct', 12.90, 6, 'mango,pulp', 'Pacote 4x100g.'],
        ['Camarão Cinza', 'Pescados Atlântico', 'pct', 78.90, 1, 'shrimp,frozen', 'Pacote 1kg, M.', false],
        ['Filé de Tilápia', 'Copescal', 'pct', 38.90, 2, 'fish,fillet', 'Pacote 1kg.'],
        ['Filé de Salmão', 'Salmar', 'pct', 89.90, 1, 'salmon,frozen', 'Pacote 500g.'],
        ['Bacalhau Dessalgado', 'Riberalves', 'pct', 78.90, 1, 'cod,fish', 'Pacote 500g.'],
        ['Atum em Posta', 'Pescados Atlântico', 'pct', 48.90, 2, 'tuna,steak', 'Pacote 500g.'],
        ['Vegetais Congelados Mix', 'Hortz', 'pct', 14.90, 6, 'vegetables,frozen', 'Pacote 600g.'],
        ['Brócolis Congelado', 'Hortz', 'pct', 12.90, 6, 'broccoli,frozen', 'Pacote 500g.'],
        ['Sorvete Creme', 'Kibon', 'pote', 24.90, 4, 'icecream,vanilla', 'Pote 1.5L.'],
        ['Sorvete Chocolate', 'Kibon', 'pote', 24.90, 4, 'icecream,chocolate', 'Pote 1.5L.'],
        ['Sorvete Morango', 'Kibon', 'pote', 24.90, 4, 'icecream,strawberry', 'Pote 1.5L.'],
        ['Açaí Cremoso', 'Petruz', 'pote', 22.90, 4, 'acai,frozen', 'Pote 1L, com guaraná.'],
      ]),
    },
    {
      id: 'cafes',
      name: 'Café & Cia',
      tagline: 'Cafés especiais, chás e cápsulas',
      category: 'Cafés e Chás',
      whatsapp: '5511990000002',
      address: 'Rua dos Cafés, 333',
      cnpj: '11.222.333/0001-11',
      hero: 'coffee,beans',
      products: expand([
        ['Café Espresso em Grãos', 'Melitta', 'pct', 32.90, 4, 'coffee,beans', 'Pacote 500g, blend italiano.'],
        ['Café Gourmet Moído', 'Pilão', 'pct', 24.90, 4, 'coffee,ground', 'Pacote 500g, gourmet.'],
        ['Café Tradicional Moído', 'Melitta', 'pct', 18.90, 6, 'coffee,bag', 'Pacote 500g.'],
        ['Café Extraforte', '3 Corações', 'pct', 19.90, 6, 'coffee,strong', 'Pacote 500g.'],
        ['Café Descafeinado', 'Melitta', 'pct', 28.90, 4, 'coffee,decaf', 'Pacote 250g.'],
        ['Café Orgânico', 'Café Orfeu', 'pct', 38.90, 2, 'coffee,organic', 'Pacote 250g, microlote.'],
        ['Café em Cápsulas', 'L Or', 'cx', 24.90, 6, 'coffee,capsule', 'Caixa 10 cápsulas, ristretto.'],
        ['Café em Cápsulas Lungo', 'L Or', 'cx', 24.90, 6, 'capsule,coffee', 'Caixa 10 cápsulas.'],
        ['Café em Cápsulas Decaf', 'L Or', 'cx', 26.90, 4, 'decaf,capsule', 'Caixa 10 cápsulas.'],
        ['Café Solúvel', 'Nescafé', 'pote', 18.90, 4, 'instant,coffee', 'Pote 100g.'],
        ['Café Solúvel Premium', 'Nescafé Origens', 'pote', 32.90, 4, 'coffee,jar', 'Pote 100g, etíope.'],
        ['Cappuccino Pronto', '3 Corações', 'pct', 14.90, 4, 'cappuccino', 'Pacote 200g, com chocolate.'],
        ['Mocha em Pó', 'Melitta', 'pct', 18.90, 4, 'mocha,powder', 'Pacote 200g.'],
        ['Filtro de Papel 102', 'Melitta', 'cx', 8.90, 6, 'filter,coffee', 'Caixa com 30.'],
        ['Filtro de Papel 103', 'Melitta', 'cx', 9.90, 6, 'filter,paper', 'Caixa com 30.'],
        ['Chá Verde Sachê', 'Twinings', 'cx', 22.90, 4, 'green,tea,bag', 'Caixa com 25 sachês.'],
        ['Chá Camomila', 'Leão', 'cx', 8.90, 6, 'chamomile,tea', 'Caixa com 25 sachês.'],
        ['Chá de Hibisco', 'Dr. Oetker', 'cx', 12.90, 4, 'hibiscus,tea', 'Caixa 15 sachês.'],
        ['Chá Boldo', 'Leão', 'cx', 8.90, 6, 'tea,bag', 'Caixa com 25 sachês.'],
        ['Chá Erva-doce', 'Leão', 'cx', 8.90, 6, 'fennel,tea', 'Caixa com 25 sachês.'],
        ['Chá Mate Natural', 'Leão', 'cx', 9.90, 6, 'mate,tea', 'Caixa 250g, queimado.'],
        ['Chá Preto Sachê', 'Twinings', 'cx', 22.90, 4, 'black,tea', 'Caixa com 25, English Breakfast.'],
        ['Chá Earl Grey', 'Twinings', 'cx', 22.90, 4, 'earl,grey', 'Caixa com 25 sachês.'],
        ['Erva Mate para Chimarrão', 'Barão', 'pct', 18.90, 4, 'yerba,mate', 'Pacote 1kg, tradicional.'],
        ['Erva Mate Tereré', 'Barão', 'pct', 14.90, 4, 'yerba,terere', 'Pacote 500g.'],
        ['Açúcar Demerara', 'Native', 'pct', 12.90, 6, 'sugar,brown', 'Pacote 1kg.'],
        ['Adoçante Líquido', 'Linea', 'gf', 14.90, 4, 'sweetener', 'Frasco 100ml.'],
        ['Mel de Abelha', 'Apis Vida', 'pote', 22.90, 4, 'honey,jar', 'Pote 500g.'],
        ['Canela em Pó', 'Kitano', 'pct', 6.90, 6, 'cinnamon,powder', 'Pacote 30g.'],
        ['Cacau em Pó', 'Garoto', 'lata', 18.90, 4, 'cocoa,powder', 'Lata 200g, 100% cacau.'],
        ['Leite Vegetal de Aveia', 'Nutty', 'cx', 14.90, 4, 'oat,milk', 'Caixa 1L.'],
        ['Leite Vegetal de Amêndoas', 'Nutty', 'cx', 22.90, 4, 'almond,milk', 'Caixa 1L.', false],
        ['Xarope para Café', 'Monin', 'gf', 38.90, 2, 'syrup,coffee', 'Garrafa 700ml, baunilha.'],
        ['Cobertura Chocolate', 'Hershey s', 'gf', 14.90, 4, 'chocolate,sauce', 'Frasco 200g.'],
        ['Açúcar para Café', 'União', 'pct', 8.90, 6, 'sugar,packet', 'Caixa 100 sachês.'],
      ]),
    },
    {
      id: 'pescados',
      name: 'Distribuidora Sul Mar',
      tagline: 'Pescados frescos e congelados',
      category: 'Pescados',
      whatsapp: '5511990000003',
      address: 'Mercado do Peixe, Box 14',
      cnpj: '22.333.444/0001-12',
      hero: 'fish,seafood',
      products: expand([
        ['Salmão Fresco em Posta', 'Salmar', 'kg', 119.90, 1, 'salmon,steak', 'Posta de 200g, refrigerado.'],
        ['Salmão Fresco em Filé', 'Salmar', 'kg', 129.90, 1, 'salmon,fillet', 'Filé sem espinha.'],
        ['Atum Fresco', 'Atlântico', 'kg', 98.90, 1, 'tuna,fresh', 'Posta de 200g, refrigerado.'],
        ['Pescada Branca', 'Atlântico', 'kg', 38.90, 1, 'fish,white', 'Inteira eviscerada.'],
        ['Tilápia Filé', 'Copescal', 'kg', 48.90, 1, 'tilapia,fish', 'Filé fresco, sem espinha.'],
        ['Tilápia Inteira', 'Copescal', 'kg', 28.90, 1, 'fish,whole', 'Inteira eviscerada.'],
        ['Bacalhau do Porto', 'Riberalves', 'kg', 178.90, 0.5, 'cod,fish', 'Salgado, importado.'],
        ['Bacalhau Dessalgado', 'Riberalves', 'kg', 148.90, 0.5, 'cod,fillet', 'Pronto para uso.'],
        ['Camarão Médio', 'Pescados Atlântico', 'kg', 78.90, 0.5, 'shrimp,small', 'Cinza, com casca.'],
        ['Camarão Grande', 'Pescados Atlântico', 'kg', 128.90, 0.5, 'shrimp,large', 'Sete-barbas.'],
        ['Camarão Limpo', 'Pescados Atlântico', 'kg', 158.90, 0.5, 'shrimp,clean', 'Sem casca, sem cabeça.'],
        ['Lula Limpa', 'Pescados Atlântico', 'kg', 68.90, 1, 'squid,seafood', 'Anel, congelada.'],
        ['Polvo Inteiro', 'Pescados Atlântico', 'kg', 98.90, 1, 'octopus', 'Importado, peça 1kg.', false],
        ['Mexilhão sem Concha', 'Pescados Atlântico', 'kg', 38.90, 1, 'mussel,shell', 'Embalagem 1kg.'],
        ['Marisco', 'Pescados Atlântico', 'kg', 32.90, 1, 'clams,seafood', 'Sem concha, congelado.'],
        ['Vieira', 'Pescados Atlântico', 'kg', 138.90, 0.5, 'scallop,seafood', 'Importada, congelada.'],
        ['Sardinha Fresca', 'Atlântico', 'kg', 22.90, 1, 'sardine,fresh', 'Inteira, refrigerada.'],
        ['Pintado em Posta', 'Pescados do Pantanal', 'kg', 58.90, 1, 'fish,large', 'Posta de 200g.'],
        ['Robalo Inteiro', 'Atlântico', 'kg', 88.90, 1, 'fish,whole', 'Inteiro eviscerado.'],
        ['Linguado em Filé', 'Atlântico', 'kg', 88.90, 1, 'fish,fillet', 'Filé fresco.'],
        ['Pacu', 'Pescados do Pantanal', 'kg', 48.90, 1, 'fish,plate', 'Inteiro, eviscerado.'],
        ['Tambaqui', 'Pescados do Pantanal', 'kg', 52.90, 1, 'fish,grey', 'Inteiro, eviscerado.'],
        ['Truta Inteira', 'Truticultura SP', 'kg', 58.90, 1, 'trout,fish', 'Eviscerada, peso médio 400g.'],
        ['Cação em Filé', 'Atlântico', 'kg', 38.90, 1, 'fish,grilled', 'Filé limpo.'],
        ['Merluza em Filé', 'Atlântico', 'kg', 32.90, 1, 'merluza,fish', 'Filé congelado.'],
        ['Anchova', 'Atlântico', 'kg', 36.90, 1, 'anchovy,fish', 'Inteira, refrigerada.'],
        ['Lagosta', 'Pescados Atlântico', 'kg', 218.90, 0.5, 'lobster,seafood', 'Inteira, congelada.', false],
        ['Caranguejo Limpo', 'Pescados do Norte', 'kg', 58.90, 1, 'crab,meat', 'Pronto para uso.'],
        ['Casquinha de Siri', 'Pescados do Norte', 'cx', 12.90, 6, 'crab,casquinha', 'Pronta para forno, 100g.'],
        ['Sushi Combinado', 'Sushi & Cia', 'pct', 89.90, 1, 'sushi,combo', 'Combo 24 peças.'],
        ['Sashimi de Salmão', 'Sushi & Cia', 'pct', 78.90, 1, 'sashimi,salmon', '15 fatias frescas.'],
        ['Hashi Descartável', 'Sushi & Cia', 'pct', 14.90, 4, 'chopsticks', 'Pacote 100 pares.'],
        ['Molho Shoyu', 'Sakura', 'gf', 12.90, 6, 'soy,sauce', 'Garrafa 500ml.'],
        ['Wasabi em Pasta', 'Sakura', 'gf', 18.90, 4, 'wasabi,paste', 'Bisnaga 43g.'],
        ['Gengibre em Conserva', 'Sakura', 'pote', 14.90, 4, 'ginger,pickled', 'Pote 200g.'],
      ]),
    },
  ];

  // Add the supplier id back into each product so cart logic can verify origin.
  suppliers.forEach((s) => {
    s.products.forEach((p) => { p.supplierId = s.id; });
  });

  window.SUPPLIERS = suppliers;
  window.findSupplier = (id) => suppliers.find((s) => s.id === id);
})();
